/// Integration tests for backend-c.
///
/// The backend emits 4 files:
///   files[0] = CMakeLists.txt
///   files[1] = include/<module>.h
///   files[2] = src/<module>.c
///   files[3] = test/test_roundtrip.c

use std::path::PathBuf;
use backend_c::CBackend;
use cddlc_codegen::{Backend, CodegenOptions};
use cddlc_ir::lower;
use cddlc_parser::parse_cddl;

// ── Helpers ───────────────────────────────────────────────────────────────────

struct GeneratedCrate {
    cmake:      String,
    header:     String,
    source:     String,
    tests:      String,
}

fn compile(src: &str) -> GeneratedCrate {
    compile_with_opts(src, CodegenOptions::default())
}

fn compile_with_opts(src: &str, opts: CodegenOptions) -> GeneratedCrate {
    let parsed  = parse_cddl(src, PathBuf::from("test.cddl")).expect("parse");
    let lowered = lower(&parsed.value, 16, 64).expect("lower");
    let out     = CBackend.generate(&lowered.module, &opts).expect("generate");
    assert_eq!(out.files.len(), 4, "expected 4 output files");
    GeneratedCrate {
        cmake:  out.files[0].content.clone(),
        header: out.files[1].content.clone(),
        source: out.files[2].content.clone(),
        tests:  out.files[3].content.clone(),
    }
}

// ── Crate structure ───────────────────────────────────────────────────────────

#[test]
fn test_emits_four_files() {
    let opts   = CodegenOptions::default();
    let parsed = parse_cddl("x = uint", PathBuf::from("t.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out    = CBackend.generate(&lowered.module, &opts).unwrap();
    assert_eq!(out.files.len(), 4);
    assert!(out.files[0].path.ends_with("CMakeLists.txt"));
    assert!(out.files[1].path.ends_with(".h"));
    assert!(out.files[2].path.ends_with(".c"));
    assert!(out.files[3].path.ends_with("test_roundtrip.c"));
}

#[test]
fn test_crate_dir_named_after_module() {
    let opts   = CodegenOptions::default();
    let parsed = parse_cddl("x = uint", PathBuf::from("sensor.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out    = CBackend.generate(&lowered.module, &opts).unwrap();
    assert!(out.files[0].path.starts_with("sensor-cbor/"));
    assert!(out.files[1].path.starts_with("sensor-cbor/include/"));
    assert!(out.files[2].path.starts_with("sensor-cbor/src/"));
    assert!(out.files[3].path.starts_with("sensor-cbor/test/"));
}

// ── CMakeLists.txt ────────────────────────────────────────────────────────────

#[test]
fn test_cmake_generated_comment() {
    let g = compile("x = uint");
    assert!(g.cmake.contains("@generated by cddlc"));
}

#[test]
fn test_cmake_has_project() {
    let g = compile("x = uint");
    assert!(g.cmake.contains("project("));
}

#[test]
fn test_cmake_c11_standard() {
    let g = compile("x = uint");
    assert!(g.cmake.contains("CMAKE_C_STANDARD 11"));
}

#[test]
fn test_cmake_nanocbor_dependency() {
    let g = compile("x = uint");
    assert!(g.cmake.contains("nanocbor") || g.cmake.contains("NanoCBOR"));
}

#[test]
fn test_cmake_enable_testing() {
    let g = compile("x = uint");
    assert!(g.cmake.contains("enable_testing"));
}

// ── Header file ───────────────────────────────────────────────────────────────

#[test]
fn test_header_generated_comment() {
    let g = compile("x = uint");
    assert!(g.header.contains("@generated by cddlc"));
}

#[test]
fn test_header_include_guard() {
    let g = compile("x = uint");
    assert!(g.header.contains("#ifndef"));
    assert!(g.header.contains("#define"));
    assert!(g.header.contains("#endif"));
}

#[test]
fn test_header_stdint_include() {
    let g = compile("x = uint");
    assert!(g.header.contains("#include <stdint.h>"));
}

#[test]
fn test_header_nanocbor_include() {
    let g = compile("x = uint");
    assert!(g.header.contains("nanocbor"));
}

#[test]
fn test_header_error_enum() {
    let g = compile("x = uint");
    assert!(g.header.contains("_err_t"));
    assert!(g.header.contains("_OK"));
    assert!(g.header.contains("_ERR_TAG"));
    assert!(g.header.contains("_ERR_VALIDATION"));
}

#[test]
fn test_header_field_error_struct() {
    let g = compile("x = uint");
    assert!(g.header.contains("_field_err_t"));
    assert!(g.header.contains("field;"));
}

#[test]
fn test_header_callbacks_struct() {
    let g = compile("x = uint");
    assert!(g.header.contains("_callbacks_t"));
    assert!(g.header.contains("on_error"));
    assert!(g.header.contains("on_unknown_field"));
}

#[test]
fn test_header_cbor_str_type() {
    let g = compile("x = uint");
    assert!(g.header.contains("cbor_str_t"));
}

// ── Struct declaration ────────────────────────────────────────────────────────

#[test]
fn test_struct_typedef() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.header.contains("typedef struct {"));
    assert!(g.header.contains("sensor_t;"));
}

#[test]
fn test_struct_uint_field() {
    let g = compile("sensor = { id: uint }");
    assert!(g.header.contains("uint64_t id;"));
}

#[test]
fn test_struct_float_field() {
    let g = compile("sensor = { value: float32 }");
    assert!(g.header.contains("float value;"));
}

#[test]
fn test_struct_tstr_field() {
    let g = compile("msg = { label: tstr }");
    assert!(g.header.contains("cbor_str_t label;"));
}

#[test]
fn test_struct_optional_field_has_present_flag() {
    let g = compile("msg = { id: uint, ? label: tstr }");
    assert!(g.header.contains("label_present;") || g.header.contains("bool label_present"));
}

// ── Enum declaration ──────────────────────────────────────────────────────────

#[test]
fn test_enum_tag_enum() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.header.contains("status_tag_t;") || g.header.contains("_tag_t"));
}

#[test]
fn test_enum_union_struct() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.header.contains("union {") || g.header.contains("status_t;"));
}

#[test]
fn test_enum_variant_constants() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.header.contains("STATUS_OK") || g.header.contains("_OK"));
    assert!(g.header.contains("STATUS_WARN") || g.header.contains("_WARN"));
}

// ── Array declaration ─────────────────────────────────────────────────────────

#[test]
fn test_array_struct_with_items_and_count() {
    let g = compile("; @capacity 8\nreadings = [* float32]");
    assert!(g.header.contains("items[8]") || g.header.contains("items["));
    assert!(g.header.contains("count;"));
}

// ── Alias declaration ─────────────────────────────────────────────────────────

#[test]
fn test_simple_alias_typedef() {
    let g = compile("device-id = uint");
    assert!(g.header.contains("device_id_t"));
    assert!(g.header.contains("uint64_t"));
}

#[test]
fn test_constrained_alias_newtype() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.header.contains("device_id_t"));
}

// ── Tagged types ──────────────────────────────────────────────────────────────

#[test]
fn test_tagged_encode_emits_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.source.contains("nanocbor_fmt_tag") && g.source.contains("1"));
}

#[test]
fn test_tagged_decode_verifies_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.source.contains("nanocbor_get_tag"));
    assert!(g.source.contains("ERR_TAG") || g.source.contains("return -1"));
}

// ── Function declarations ─────────────────────────────────────────────────────

#[test]
fn test_encode_fn_declaration() {
    let g = compile("sensor = { id: uint }");
    assert!(g.header.contains("_encode("));
    assert!(g.header.contains("nanocbor_encoder_t"));
}

#[test]
fn test_decode_fn_declaration() {
    let g = compile("sensor = { id: uint }");
    assert!(g.header.contains("_decode("));
    assert!(g.header.contains("nanocbor_value_t"));
}

// ── Source file ───────────────────────────────────────────────────────────────

#[test]
fn test_source_generated_comment() {
    let g = compile("x = uint");
    assert!(g.source.contains("@generated by cddlc"));
}

#[test]
fn test_source_includes_header() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("#include"));
    assert!(g.source.contains(".h\""));
}

#[test]
fn test_struct_encode_maps_fields() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.source.contains("nanocbor_fmt_map"));
    assert!(g.source.contains("\"id\"") || g.source.contains("id"));
}

#[test]
fn test_struct_decode_map_entry() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("nanocbor_enter_map"));
}

#[test]
fn test_unknown_field_skipped() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("nanocbor_skip"));
    assert!(g.source.contains("on_unknown_field"));
}

#[test]
fn test_validation_in_decode() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.source.contains("ERR_VALIDATION") || g.source.contains("return -1"));
}

#[test]
fn test_dcbor_sorts_keys() {
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let g = compile_with_opts("s = { b: uint, a: tstr }", opts);
    // With dCBOR, fields are sorted — "a" should appear before "b" in encode
    let a_pos = g.source.find("\"a\"").unwrap_or(usize::MAX);
    let b_pos = g.source.find("\"b\"").unwrap_or(0);
    assert!(a_pos < b_pos, "dCBOR: 'a' should be encoded before 'b'");
}

// ── Test file ─────────────────────────────────────────────────────────────────

#[test]
fn test_roundtrip_generated_comment() {
    let g = compile("x = uint");
    assert!(g.tests.contains("@generated by cddlc"));
}

#[test]
fn test_roundtrip_includes_header() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("#include"));
}

#[test]
fn test_roundtrip_has_test_functions() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("test_") && g.tests.contains("_roundtrip"));
}

#[test]
fn test_roundtrip_encode_decode_cycle() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("nanocbor_encoder_init"));
    assert!(g.tests.contains("nanocbor_decoder_init"));
    assert!(g.tests.contains("_encode("));
    assert!(g.tests.contains("_decode("));
}

#[test]
fn test_roundtrip_has_main() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("int main("));
}

#[test]
fn test_iot_schema() {
    let g = compile(r#"
sensor-message = {
    version:   uint,
    device-id: device-id,
    timestamp: #6.1(uint),
}
device-id = tstr .size 16
"#);
    assert!(g.header.contains("sensor_message_t"));
    assert!(g.header.contains("device_id_t"));
    assert!(g.source.contains("nanocbor_fmt_tag") || g.source.contains("1"));
}
