/// C backend for cddlc.
///
/// Emits a C library crate:
///   <module>-cbor/
///     CMakeLists.txt
///     include/<module>.h      ← type declarations + callback API
///     src/<module>.c          ← encode/decode implementations
///     test/test_roundtrip.c   ← roundtrip tests (Unity framework)

use cddlc_codegen::{
    capacity_value, constraint_to_c_check, primitive_to_c,
    to_screaming_snake, to_snake_case,
    Backend, CodegenError, CodegenOptions, CodegenOutput, GeneratedFile,
    IndentWriter,
};
use cddlc_ir::{
    AliasDef, ArrayDef, Capacity, Constraint, EnumDef,
    IrModule, Occurrence, Primitive, StructDef, TypeDef, TypeRef,
};

pub struct CBackend;

impl Backend for CBackend {
    fn language_name(&self) -> &str { "C" }
    fn file_extension(&self) -> &str { "h" }

    fn generate(
        &self,
        module: &IrModule,
        opts:   &CodegenOptions,
    ) -> Result<CodegenOutput, CodegenError> {
        let name     = module.name.as_str();
        let crate_dir = format!("{name}-cbor");

        Ok(CodegenOutput {
            files: vec![
                GeneratedFile {
                    path:    format!("{crate_dir}/CMakeLists.txt"),
                    content: emit_cmake(name, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/include/{name}.h"),
                    content: emit_header(module, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/include/nanocbor_compat.h"),
                    content: NANOCBOR_MACOS_COMPAT_H.to_string(),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/src/{name}.c"),
                    content: emit_source(module, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/test/test_roundtrip.c"),
                    content: emit_tests(module, opts),
                },
            ],
        })
    }
}

// ── macOS compat header ───────────────────────────────────────────────────────

/// Compatibility shim for nanocbor on macOS.
///
/// nanocbor/config.h defaults to Linux's `endian.h` and uses `be64toh`,
/// `htobe64`, etc. which do not exist on macOS.  This header overrides those
/// macros to use the macOS `<libkern/OSByteOrder.h>` equivalents.
const NANOCBOR_MACOS_COMPAT_H: &str = r#"/* @generated by cddlc — do not edit manually */
/* macOS compatibility shim for nanocbor byte-order functions */
#pragma once
#include <libkern/OSByteOrder.h>
/* Override nanocbor/config.h default so it does not request Linux endian.h */
#define NANOCBOR_BYTEORDER_HEADER <libkern/OSByteOrder.h>
/* Map Linux byte-order functions to their macOS equivalents */
#define be16toh(x) OSSwapBigToHostInt16(x)
#define be32toh(x) OSSwapBigToHostInt32(x)
#define be64toh(x) OSSwapBigToHostInt64(x)
#define htobe16(x) OSSwapHostToBigInt16(x)
#define htobe32(x) OSSwapHostToBigInt32(x)
#define htobe64(x) OSSwapHostToBigInt64(x)
#define le16toh(x) OSSwapLittleToHostInt16(x)
#define le32toh(x) OSSwapLittleToHostInt32(x)
#define le64toh(x) OSSwapLittleToHostInt64(x)
#define htole16(x) OSSwapHostToLittleInt16(x)
#define htole32(x) OSSwapHostToLittleInt32(x)
#define htole64(x) OSSwapHostToLittleInt64(x)
"#;

// ── CMakeLists.txt ────────────────────────────────────────────────────────────

fn emit_cmake(name: &str, _opts: &CodegenOptions) -> String {
    format!(r#"# @generated by cddlc — do not edit manually
cmake_minimum_required(VERSION 3.16)
project({name}_cbor C)

set(CMAKE_C_STANDARD 11)

# nanocbor — fetch source and compile directly
include(FetchContent)
FetchContent_Declare(nanocbor
    GIT_REPOSITORY https://github.com/bergzand/NanoCBOR.git
    GIT_TAG        master
)
FetchContent_GetProperties(nanocbor)
if(NOT nanocbor_POPULATED)
    FetchContent_Populate(nanocbor)
endif()

file(GLOB NANOCBOR_SOURCES "${{nanocbor_SOURCE_DIR}}/src/*.c")

add_library({name}_cbor
    src/{name}.c
    ${{NANOCBOR_SOURCES}}
)
target_include_directories({name}_cbor PUBLIC include ${{nanocbor_SOURCE_DIR}}/include)

# macOS: nanocbor uses Linux-only byte-order functions; force-include a compat shim
if(APPLE)
    target_compile_options({name}_cbor PRIVATE
        -include "${{CMAKE_CURRENT_SOURCE_DIR}}/include/nanocbor_compat.h"
    )
endif()

# Tests (requires Unity test framework)
enable_testing()
add_executable(test_roundtrip test/test_roundtrip.c)
target_link_libraries(test_roundtrip {name}_cbor)
add_test(NAME roundtrip COMMAND test_roundtrip)
"#)
}

// ── Header file ───────────────────────────────────────────────────────────────

fn emit_header(module: &IrModule, opts: &CodegenOptions) -> String {
    let name    = module.name.as_str();
    let guard   = format!("{}_H", name.to_uppercase().replace('-', "_"));
    let mut w   = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line(&format!("#ifndef {guard}"));
    w.line(&format!("#define {guard}"));
    w.blank();
    w.line("#include <stdint.h>");
    w.line("#include <stddef.h>");
    w.line("#include <stdbool.h>");
    w.line("#include <nanocbor/nanocbor.h>");
    w.blank();

    // ── Common types ──────────────────────────────────────────────────────────
    w.line("/* Zero-copy string slice (points into decode buffer) */");
    w.line("typedef struct { const char *ptr; size_t len; } cbor_str_t;");
    w.blank();
    w.line("/* Zero-copy byte slice */");
    w.line("typedef struct { const uint8_t *ptr; size_t len; } cbor_bytes_t;");
    w.blank();

    // ── Error codes ───────────────────────────────────────────────────────────
    w.line("typedef enum {");
    w.indent();
    w.line(&format!("{}_OK = 0,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_TYPE,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_VALUE,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_MISSING,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_OVERFLOW,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_UTF8,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_UNKNOWN_FIELD,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_TAG,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_VALIDATION,", to_screaming_snake(name)));
    w.dedent();
    w.line(&format!("}} {}_err_t;", to_snake_case(name)));
    w.blank();

    // ── Field error ───────────────────────────────────────────────────────────
    w.line("typedef struct {");
    w.indent();
    w.line(&format!("{}_err_t  code;", to_snake_case(name)));
    w.line("const char     *field;");
    w.line("size_t          index;");
    w.dedent();
    w.line(&format!("}} {}_field_err_t;", to_snake_case(name)));
    w.blank();

    // ── Callbacks ─────────────────────────────────────────────────────────────
    w.line("/* Callbacks provided by the caller */");
    w.line("typedef struct {");
    w.indent();
    w.line(&format!(
        "void (*on_error)(void *ctx, {}_field_err_t err);",
        to_snake_case(name)
    ));
    w.line("void (*on_unknown_field)(void *ctx, cbor_str_t key);");
    w.dedent();
    w.line(&format!("}} {}_callbacks_t;", to_snake_case(name)));
    w.blank();

    // ── Type declarations ─────────────────────────────────────────────────────
    for (_, def) in &module.types {
        emit_type_decl_h(&mut w, def, name, opts);
        w.blank();
    }

    // ── Function declarations ─────────────────────────────────────────────────
    w.line("/* Encode/decode function declarations */");
    for (_, def) in &module.types {
        emit_fn_decls(&mut w, def, name, opts);
    }
    w.blank();

    w.line(&format!("#endif /* {guard} */"));
    w.finish()
}

fn emit_type_decl_h(w: &mut IndentWriter, def: &TypeDef, _mod_name: &str, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct_decl(w, s, opts),
        TypeDef::Enum(e)   => emit_enum_decl(w, e, opts),
        TypeDef::Array(a)  => emit_array_decl(w, a, opts),
        TypeDef::Alias(a)  => emit_alias_decl(w, a, opts),
        TypeDef::Map(_)    => {}
    }
}

fn emit_struct_decl(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    emit_c_doc(w, s.doc.as_deref());
    let type_name = to_snake_case(&s.name);
    w.line(&format!("typedef struct {{"));
    w.indent();
    for f in &s.fields {
        let ty_str = c_field_type(&f.ty, &f.occurrence, opts);
        let fname  = to_snake_case(&f.name);
        w.line(&format!("{ty_str} {fname};"));
        // bool present flag for optional fields
        if matches!(f.occurrence, Occurrence::Optional) {
            w.line(&format!("bool {fname}_present;"));
        }
    }
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_enum_decl(w: &mut IndentWriter, e: &EnumDef, _opts: &CodegenOptions) {
    emit_c_doc(w, e.doc.as_deref());
    let type_name = to_snake_case(&e.name);

    // Tag enum
    w.line("typedef enum {");
    w.indent();
    for (i, v) in e.variants.iter().enumerate() {
        let vname = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
        if i == e.variants.len() - 1 {
            w.line(&format!("{vname}"));
        } else {
            w.line(&format!("{vname},"));
        }
    }
    w.dedent();
    w.line(&format!("}} {type_name}_tag_t;"));
    w.blank();

    // Union struct
    w.line(&format!("typedef struct {{"));
    w.indent();
    w.line(&format!("{type_name}_tag_t tag;"));
    w.line("union {");
    w.indent();
    for v in &e.variants {
        let vname = to_snake_case(&v.name);
        match &v.ty {
            TypeRef::Primitive(Primitive::Null) => {}
            TypeRef::Primitive(p) => {
                w.line(&format!("{} {};", primitive_to_c(p), vname));
            }
            TypeRef::Named(n) => {
                w.line(&format!("{}_t {};", to_snake_case(n), vname));
            }
            _ => {}
        }
    }
    w.dedent();
    w.line("} value;");
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_array_decl(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    emit_c_doc(w, a.doc.as_deref());
    let type_name = to_snake_case(&a.name);
    let elem_ty   = typeref_to_c(&a.element, opts);
    let cap       = capacity_value(
        a.occurrence.capacity().unwrap_or(&Capacity::Bounded(opts.max_array)),
        opts.max_array,
    );
    w.line(&format!("typedef struct {{"));
    w.indent();
    w.line(&format!("{elem_ty} items[{cap}];"));
    w.line("size_t count;");
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_alias_decl(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    emit_c_doc(w, a.doc.as_deref());
    let type_name = to_snake_case(&a.name);
    if a.tagged.is_some() || !a.constraints.is_empty() {
        // Newtype struct for tagged/constrained aliases
        let inner = typeref_to_c(&a.ty, opts);
        w.line(&format!("typedef struct {{ {inner} value; }} {type_name}_t;"));
    } else {
        let inner = typeref_to_c(&a.ty, opts);
        w.line(&format!("typedef {inner} {type_name}_t;"));
    }
}

fn emit_fn_decls(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, _opts: &CodegenOptions) {
    let type_name = to_snake_case(def.name());
    let pfx       = to_snake_case(mod_name);

    w.line(&format!(
        "int {pfx}_{type_name}_encode(nanocbor_encoder_t *enc, const {type_name}_t *val);"
    ));
    w.line(&format!(
        "int {pfx}_{type_name}_decode(nanocbor_value_t *dec, {type_name}_t *out, \
         const {pfx}_callbacks_t *cb, void *ctx);"
    ));
}

// ── Source file ───────────────────────────────────────────────────────────────

fn emit_source(module: &IrModule, opts: &CodegenOptions) -> String {
    let name  = module.name.as_str();
    let mut w = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line(&format!("#include \"{name}.h\""));
    w.line("#include <string.h>");
    w.blank();

    for (_, def) in &module.types {
        w.blank();
        emit_encode_fn(&mut w, def, name, opts);
        w.blank();
        emit_decode_fn(&mut w, def, name, opts);
    }

    w.finish()
}

fn emit_encode_fn(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, opts: &CodegenOptions) {
    let type_name = to_snake_case(def.name());
    let pfx       = to_snake_case(mod_name);

    w.line(&format!(
        "int {pfx}_{type_name}_encode(nanocbor_encoder_t *enc, const {type_name}_t *val) {{"
    ));
    w.indent();

    match def {
        TypeDef::Struct(s) => {
            // Emit tag if present
            if let Some(tag) = s.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            // dCBOR: sort keys — for now emit in definition order
            let fields: Vec<_> = if opts.dcbor {
                let mut fs: Vec<_> = s.fields.iter().collect();
                fs.sort_by(|a, b| a.name.cmp(&b.name));
                fs
            } else {
                s.fields.iter().collect()
            };
            // Compute map count: required fields always present; optional only when _present flag set
            let req_count = fields.iter().filter(|f| !matches!(f.occurrence, Occurrence::Optional)).count();
            let opt_fields: Vec<_> = fields.iter().filter(|f| matches!(f.occurrence, Occurrence::Optional)).collect();
            if opt_fields.is_empty() {
                w.line(&format!("nanocbor_fmt_map(enc, {req_count}u);"));
            } else {
                let opt_sum: String = opt_fields.iter().map(|f| {
                    let fname = to_snake_case(&f.name);
                    format!("(val->{fname}_present ? 1u : 0u)")
                }).collect::<Vec<_>>().join(" + ");
                w.line(&format!("nanocbor_fmt_map(enc, {req_count}u + {opt_sum});"));
            }
            for f in &fields {
                let fname = to_snake_case(&f.name);
                if matches!(f.occurrence, Occurrence::Optional) {
                    w.line(&format!("if (val->{fname}_present) {{"));
                    w.indent();
                    w.line(&format!("nanocbor_put_tstr(enc, {:?});", f.name.as_str()));
                    emit_c_encode_field(w, &f.ty, &format!("val->{fname}"), &f.occurrence, mod_name, opts);
                    w.dedent();
                    w.line("}");
                } else {
                    w.line(&format!("nanocbor_put_tstr(enc, {:?});", f.name.as_str()));
                    emit_c_encode_field(w, &f.ty, &format!("val->{fname}"), &f.occurrence, mod_name, opts);
                }
            }
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Enum(e) => {
            if let Some(tag) = e.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            w.line(&format!("switch (val->tag) {{"));
            for v in &e.variants {
                let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
                let vname  = to_snake_case(&v.name);
                w.line(&format!("case {vconst}:"));
                w.indent();
                match &v.ty {
                    TypeRef::Primitive(Primitive::Tstr) => {
                        let s = v.name.to_lowercase().replace('_', "-");
                        w.line(&format!("nanocbor_put_tstr(enc, {:?});", s));
                    }
                    TypeRef::Primitive(Primitive::Uint) =>
                        w.line(&format!("nanocbor_fmt_uint(enc, val->value.{vname});")),
                    TypeRef::Primitive(Primitive::Int) =>
                        w.line(&format!("nanocbor_fmt_int(enc, val->value.{vname});")),
                    TypeRef::Primitive(Primitive::Bool) =>
                        w.line(&format!("nanocbor_fmt_bool(enc, val->value.{vname});")),
                    TypeRef::Primitive(Primitive::Null) =>
                        w.line("nanocbor_fmt_null(enc);"),
                    TypeRef::Named(n) => {
                        let np = to_snake_case(mod_name);
                        let tn = to_snake_case(n);
                        w.line(&format!("{np}_{tn}_encode(enc, &val->value.{vname});"));
                    }
                    _ => w.line("nanocbor_fmt_null(enc);"),
                }
                w.line("break;");
                w.dedent();
            }
            w.line("}");
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Array(a) => {
            if let Some(tag) = a.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            w.line("nanocbor_fmt_array(enc, val->count);");
            w.line("for (size_t i = 0; i < val->count; i++) {");
            w.indent();
            emit_c_encode_field(w, &a.element, "val->items[i]", &Occurrence::Required, mod_name, opts);
            w.dedent();
            w.line("}");
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Alias(a) => {
            if let Some(tag) = a.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            let inner_expr = if a.tagged.is_some() || !a.constraints.is_empty() {
                "val->value".to_string()
            } else {
                "(*val)".to_string()
            };
            emit_c_encode_field(w, &a.ty, &inner_expr, &Occurrence::Required, mod_name, opts);
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Map(_) => {
            w.line("return NANOCBOR_OK;");
        }
    }

    w.dedent();
    w.line("}");
}

fn emit_c_encode_field(
    w:        &mut IndentWriter,
    ty:       &TypeRef,
    expr:     &str,
    occ:      &Occurrence,
    mod_name: &str,
    opts:     &CodegenOptions,
) {
    match ty {
        TypeRef::Primitive(p) => {
            let call = c_encode_call(p, expr);
            w.line(&format!("{call};"));
        }
        TypeRef::Named(n) => {
            let pfx = to_snake_case(mod_name);
            let tn  = to_snake_case(n);
            w.line(&format!("{pfx}_{tn}_encode(enc, &{expr});"));
        }
        TypeRef::Tagged(tag, inner) => {
            w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            emit_c_encode_field(w, inner, expr, occ, mod_name, opts);
        }
        TypeRef::Choice(_) => {
            w.line("/* choice encode */");
        }
    }
}

fn c_encode_call(p: &Primitive, expr: &str) -> String {
    match p {
        Primitive::Bool               => format!("nanocbor_fmt_bool(enc, {expr})"),
        Primitive::Null | Primitive::Undefined => "nanocbor_fmt_null(enc)".into(),
        Primitive::Uint               => format!("nanocbor_fmt_uint(enc, {expr})"),
        Primitive::Int                => format!("nanocbor_fmt_int(enc, {expr})"),
        Primitive::Float32            => format!("nanocbor_fmt_float(enc, {expr})"),
        Primitive::Float64 | Primitive::Float => format!("nanocbor_fmt_double(enc, {expr})"),
        Primitive::Float16            => format!("nanocbor_fmt_float(enc, {expr})"),
        Primitive::Bstr | Primitive::Any =>
            format!("nanocbor_put_bstr(enc, {expr}.ptr, {expr}.len)"),
        Primitive::Tstr               =>
            format!("nanocbor_put_tstrn(enc, {expr}.ptr, {expr}.len)"),
    }
}

fn emit_decode_fn(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, opts: &CodegenOptions) {
    let type_name = to_snake_case(def.name());
    let pfx       = to_snake_case(mod_name);
    let pfx_upper = to_screaming_snake(mod_name);

    w.line(&format!(
        "int {pfx}_{type_name}_decode(nanocbor_value_t *dec, {type_name}_t *out, \
         const {pfx}_callbacks_t *cb, void *ctx) {{"
    ));
    w.indent();
    w.line("int rc;");
    w.line(&format!("(void)cb; (void)ctx;"));

    match def {
        TypeDef::Struct(s) => {
            // Tag verification
            if let Some(tag) = s.tagged {
                w.line("{");
                w.indent();
                w.line("uint32_t tag;");
                w.line("if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("if (tag != {}) {{", tag.0));
                w.indent();
                w.line(&format!(
                    "if (cb && cb->on_error) cb->on_error(ctx, ({pfx}_field_err_t){{{pfx_upper}_ERR_TAG, \"{type_name}\", 0}});"
                ));
                w.line("return -1;");
                w.dedent();
                w.line("}");
                w.dedent();
                w.line("}");
            }

            w.line("nanocbor_value_t map;");
            w.line("if (nanocbor_enter_map(dec, &map) < 0) return -1;");
            w.blank();

            // Zero-init the output
            w.line(&format!("memset(out, 0, sizeof({type_name}_t));"));
            w.blank();

            w.line("while (!nanocbor_at_end(&map)) {");
            w.indent();
            w.line("const uint8_t *key_ptr; size_t key_len;");
            w.line("if (nanocbor_get_tstr(&map, &key_ptr, &key_len) < 0) return -1;");
            w.blank();

            for f in &s.fields {
                let fname  = to_snake_case(&f.name);
                let fkey   = f.name.as_str();
                w.line(&format!(
                    "if (key_len == {} && memcmp(key_ptr, {:?}, {}) == 0) {{",
                    fkey.len(), fkey, fkey.len()
                ));
                w.indent();
                emit_c_decode_field(w, &f.ty, &format!("out->{fname}"), &f.constraints, &fname, &pfx, &pfx_upper, "&map", opts);
                if matches!(f.occurrence, Occurrence::Optional) {
                    w.line(&format!("out->{fname}_present = true;"));
                }
                w.dedent();
                w.line("} else");
            }
            // Unknown field handler
            w.line("{");
            w.indent();
            w.line("if (cb && cb->on_unknown_field) {");
            w.indent();
            w.line("cbor_str_t uk = { (const char*)key_ptr, key_len };");
            w.line("cb->on_unknown_field(ctx, uk);");
            w.dedent();
            w.line("}");
            w.line("nanocbor_skip(&map);");
            w.dedent();
            w.line("}");

            w.dedent();
            w.line("}"); // while

            // Check required fields
            for f in &s.fields {
                if matches!(f.occurrence, Occurrence::Required) {
                    let fname = to_snake_case(&f.name);
                    // Simple check: for numeric fields, can't easily detect missing
                    // For pointer fields, check for NULL
                    match &f.ty {
                        TypeRef::Primitive(Primitive::Tstr | Primitive::Bstr) => {
                            w.line(&format!("if (!out->{fname}.ptr) {{"));
                            w.indent();
                            w.line(&format!(
                                "if (cb && cb->on_error) cb->on_error(ctx, ({pfx}_field_err_t){{{pfx_upper}_ERR_MISSING, {:?}, 0}});",
                                f.name.as_str()
                            ));
                            w.line("return -1;");
                            w.dedent();
                            w.line("}");
                        }
                        _ => {}
                    }
                }
            }

            w.line("nanocbor_leave_container(dec, &map);");
            w.line("return NANOCBOR_OK;");
        }

        TypeDef::Enum(e) => {
            if let Some(tag) = e.tagged {
                w.line("{");
                w.indent();
                w.line("uint32_t tag;");
                w.line("if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("if (tag != {}) return -1;", tag.0));
                w.dedent();
                w.line("}");
            }

            // Peek at type
            w.line("uint8_t major = nanocbor_get_type(dec);");
            w.line("if (major == NANOCBOR_TYPE_TSTR) {");
            w.indent();
            w.line("const uint8_t *s; size_t slen;");
            w.line("if (nanocbor_get_tstr(dec, &s, &slen) < 0) return -1;");
            for v in &e.variants {
                if matches!(&v.ty, TypeRef::Primitive(Primitive::Tstr)) {
                    let cddl_str = v.name.to_lowercase().replace('_', "-");
                    let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
                    w.line(&format!(
                        "if (slen == {} && memcmp(s, {:?}, {}) == 0) {{ out->tag = {vconst}; return NANOCBOR_OK; }}",
                        cddl_str.len(), cddl_str, cddl_str.len()
                    ));
                }
            }
            w.line("return -1; /* unknown variant */");
            w.dedent();
            w.line("} else if (major == NANOCBOR_TYPE_UINT || major == NANOCBOR_TYPE_NINT) {");
            w.indent();
            for v in &e.variants {
                if matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)) {
                    let vname  = to_snake_case(&v.name);
                    let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
                    w.line(&format!("if (nanocbor_get_int32(dec, (int32_t*)&out->value.{vname}) < 0) return -1;"));
                    w.line(&format!("out->tag = {vconst};"));
                    w.line("return NANOCBOR_OK;");
                    break;
                }
            }
            w.line("return -1;");
            w.dedent();
            w.line("}");
            w.line("return -1;");
        }

        TypeDef::Array(a) => {
            if let Some(tag) = a.tagged {
                w.line("{");
                w.indent();
                w.line("uint32_t tag;");
                w.line("if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("if (tag != {}) return -1;", tag.0));
                w.dedent();
                w.line("}");
            }
            let cap = capacity_value(
                a.occurrence.capacity().unwrap_or(&Capacity::Bounded(opts.max_array)),
                opts.max_array,
            );
            w.line("nanocbor_value_t arr;");
            w.line("if (nanocbor_enter_array(dec, &arr) < 0) return -1;");
            w.line("out->count = 0;");
            w.line(&format!("while (!nanocbor_at_end(&arr) && out->count < {cap}) {{"));
            w.indent();
            emit_c_decode_field(w, &a.element, "out->items[out->count]", &[], "item", &pfx, &pfx_upper, "&arr", opts);
            w.line("out->count++;");
            w.dedent();
            w.line("}");
            w.line("nanocbor_leave_container(dec, &arr);");
            w.line("return NANOCBOR_OK;");
        }

        TypeDef::Alias(a) => {
            if let Some(tag) = a.tagged {
                w.line("{");
                w.indent();
                w.line("uint32_t tag;");
                w.line("if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("if (tag != {}) {{", tag.0));
                w.indent();
                w.line(&format!(
                    "if (cb && cb->on_error) cb->on_error(ctx, ({pfx}_field_err_t){{{pfx_upper}_ERR_TAG, \"{type_name}\", 0}});"
                ));
                w.line("return -1;");
                w.dedent();
                w.line("}");
                w.dedent();
                w.line("}");
            }
            let dest = if a.tagged.is_some() || !a.constraints.is_empty() {
                "out->value".to_string()
            } else {
                "(*out)".to_string()
            };
            emit_c_decode_field(w, &a.ty, &dest, &a.constraints, &type_name, &pfx, &pfx_upper, "dec", opts);
            w.line("return NANOCBOR_OK;");
        }

        TypeDef::Map(_) => {
            w.line("return NANOCBOR_OK;");
        }
    }

    w.dedent();
    w.line("}");
}

fn emit_c_decode_field(
    w:           &mut IndentWriter,
    ty:          &TypeRef,
    dest:        &str,
    constraints: &[Constraint],
    field_name:  &str,
    pfx:         &str,
    pfx_upper:   &str,
    dec_expr:    &str,
    opts:        &CodegenOptions,
) {
    match ty {
        TypeRef::Primitive(p) => {
            let call = c_decode_call_expr(p, dest, dec_expr);
            w.line(&format!("if ({call} < 0) return -1;"));

            // Inline validation
            for c in constraints {
                if let Some(check) = c_constraint_check(c, dest, p) {
                    w.line(&format!("if (!({check})) {{"));
                    w.indent();
                    w.line(&format!(
                        "if (cb && cb->on_error) cb->on_error(ctx, ({pfx}_field_err_t){{{pfx_upper}_ERR_VALIDATION, {:?}, 0}});",
                        field_name
                    ));
                    w.line("return -1;");
                    w.dedent();
                    w.line("}");
                }
            }
        }
        TypeRef::Named(n) => {
            let tn = to_snake_case(n);
            w.line(&format!("if ({pfx}_{tn}_decode({dec_expr}, &{dest}, cb, ctx) < 0) return -1;"));
        }
        TypeRef::Tagged(tag, inner) => {
            w.line("{");
            w.indent();
            w.line("uint32_t tag;");
            w.line(&format!("if (nanocbor_get_tag({dec_expr}, &tag) < 0) return -1;"));
            w.line(&format!("if (tag != {}) return -1;", tag.0));
            emit_c_decode_field(w, inner, dest, constraints, field_name, pfx, pfx_upper, dec_expr, opts);
            w.dedent();
            w.line("}");
        }
        TypeRef::Choice(_) => {
            w.line(&format!("nanocbor_skip({dec_expr}); /* choice — skip */"));
        }
    }
}

/// Type-aware constraint check for C.
///
/// For string/byte primitives, `.size` checks the `.len` field.
/// For integer primitives, `.size N` checks that the value fits in N bytes
/// (e.g., `.size 4` on a uint → `val <= 0xFFFFFFFFU`).
fn c_constraint_check(c: &Constraint, val_expr: &str, p: &Primitive) -> Option<String> {
    match c {
        Constraint::SizeExact(n) => match p {
            Primitive::Uint => {
                let max = uint_max_for_bytes(*n)?;
                Some(format!("{val_expr} <= {max}"))
            }
            Primitive::Int => {
                let (lo, hi) = int_range_for_bytes(*n)?;
                Some(format!("{val_expr} >= {lo} && {val_expr} <= {hi}"))
            }
            _ => constraint_to_c_check(c, val_expr),
        },
        Constraint::SizeRange { .. } => match p {
            Primitive::Uint | Primitive::Int => None, // uncommon; skip
            _ => constraint_to_c_check(c, val_expr),
        },
        _ => constraint_to_c_check(c, val_expr),
    }
}

fn uint_max_for_bytes(n: usize) -> Option<String> {
    match n {
        1 => Some("0xFFU".into()),
        2 => Some("0xFFFFU".into()),
        4 => Some("0xFFFFFFFFU".into()),
        8 => None, // uint64 always fits
        _ => None,
    }
}

fn int_range_for_bytes(n: usize) -> Option<(i64, i64)> {
    match n {
        1 => Some((-128, 127)),
        2 => Some((-32768, 32767)),
        4 => Some((-2147483648, 2147483647)),
        8 => None,
        _ => None,
    }
}

fn c_decode_call_expr(p: &Primitive, dest: &str, dec_expr: &str) -> String {
    match p {
        Primitive::Bool =>
            format!("nanocbor_get_bool({dec_expr}, &{dest})"),
        Primitive::Null | Primitive::Undefined =>
            format!("nanocbor_get_null({dec_expr})"),
        Primitive::Uint =>
            format!("nanocbor_get_uint64({dec_expr}, &{dest})"),
        Primitive::Int =>
            format!("nanocbor_get_int64({dec_expr}, &{dest})"),
        Primitive::Float32 | Primitive::Float16 =>
            format!("nanocbor_get_float({dec_expr}, &{dest})"),
        Primitive::Float64 | Primitive::Float =>
            format!("nanocbor_get_double({dec_expr}, &{dest})"),
        Primitive::Tstr =>
            format!("(nanocbor_get_tstr({dec_expr}, (const uint8_t**)&{dest}.ptr, &{dest}.len))"),
        Primitive::Bstr | Primitive::Any =>
            format!("nanocbor_get_bstr({dec_expr}, &{dest}.ptr, &{dest}.len)"),
    }
}

// ── Test file ─────────────────────────────────────────────────────────────────

fn emit_tests(module: &IrModule, opts: &CodegenOptions) -> String {
    let name  = module.name.as_str();
    let pfx   = to_snake_case(name);
    let mut w = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line("/* Roundtrip encode/decode tests */");
    w.line(&format!("#include \"{name}.h\""));
    w.line("#include <assert.h>");
    w.line("#include <string.h>");
    w.line("#include <stdio.h>");
    w.blank();
    w.line("static uint8_t buf[1024];");
    w.blank();

    for (_, def) in &module.types {
        match def {
            TypeDef::Struct(s) => emit_c_struct_test(&mut w, s, &pfx, module, opts),
            TypeDef::Alias(a)  => emit_c_alias_test(&mut w, a, &pfx, opts),
            TypeDef::Array(a)  => emit_c_array_test(&mut w, a, &pfx, opts),
            TypeDef::Enum(e)   => emit_c_enum_test(&mut w, e, &pfx, opts),
            TypeDef::Map(_)    => {}
        }
        w.blank();
    }

    // main
    w.line("int main(void) {");
    w.indent();
    for (_, def) in &module.types {
        let type_name = to_snake_case(def.name());
        w.line(&format!("test_{pfx}_{type_name}_roundtrip();"));
    }
    w.line("printf(\"All roundtrip tests passed.\\n\");");
    w.line("return 0;");
    w.dedent();
    w.line("}");

    w.finish()
}

fn emit_c_struct_test(w: &mut IndentWriter, s: &StructDef, pfx: &str, module: &IrModule, opts: &CodegenOptions) {
    let type_name = to_snake_case(&s.name);
    w.line(&format!("static void test_{pfx}_{type_name}_roundtrip(void) {{"));
    w.indent();

    // Static buffers for any size-constrained tstr named fields
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        if let TypeRef::Named(n) = &f.ty {
            if let Some(n) = tstr_size_constraint_for(n, module) {
                let s_lit: String = "a".repeat(n);
                w.line(&format!("static const char _{fname}_data[{n}] = {:?};", s_lit));
            }
        }
    }

    // Build a zeroed instance
    w.line(&format!("{type_name}_t original = {{0}};"));

    // Fill in default values for each field
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        if let TypeRef::Named(n) = &f.ty {
            if let Some(n) = tstr_size_constraint_for(n, module) {
                w.line(&format!("original.{fname}.value.ptr = _{fname}_data;"));
                w.line(&format!("original.{fname}.value.len = {n};"));
                continue;
            }
        }
        let val = c_default_value(&f.ty, opts);
        if let Some(v) = val {
            w.line(&format!("original.{fname} = {v};"));
        }
    }
    w.blank();

    // Encode
    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line(&format!("assert({pfx}_{type_name}_encode(&enc, &original) == 0);"));
    w.line("size_t enc_len = nanocbor_encoded_len(&enc);");
    w.blank();

    // Decode
    w.line(&format!("{type_name}_t decoded = {{0}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line(&format!("assert({pfx}_{type_name}_decode(&dec, &decoded, NULL, NULL) == 0);"));
    w.blank();

    // Assert equality for scalar fields
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        match &f.ty {
            TypeRef::Primitive(Primitive::Tstr | Primitive::Bstr) => {
                w.line(&format!("assert(original.{fname}.len == decoded.{fname}.len);"));
            }
            TypeRef::Primitive(_) => {
                w.line(&format!("assert(original.{fname} == decoded.{fname});"));
            }
            _ => {}
        }
    }

    w.line(&format!("printf(\"{pfx}_{type_name}_roundtrip: PASS\\n\");"));
    w.dedent();
    w.line("}");
}

fn emit_c_alias_test(w: &mut IndentWriter, a: &AliasDef, pfx: &str, _opts: &CodegenOptions) {
    let type_name = to_snake_case(&a.name);
    w.line(&format!("static void test_{pfx}_{type_name}_roundtrip(void) {{"));
    w.indent();

    // For size-constrained tstr aliases, initialise with a valid-length literal
    // so that the roundtrip encode→decode passes constraint validation.
    let tstr_size = a.constraints.iter().find_map(|c| match c {
        Constraint::SizeExact(n) => Some(*n),
        Constraint::SizeRange { min: Some(n), .. } => Some(*n),
        _ => None,
    }).filter(|_| matches!(&a.ty, TypeRef::Primitive(Primitive::Tstr)));

    w.line(&format!("{type_name}_t original = {{0}};"));
    if let Some(n) = tstr_size {
        let s_lit: String = "a".repeat(n);
        w.line(&format!("static const char _val_data[{n}] = {:?};", s_lit));
        w.line(&format!("original.value.ptr = _val_data;"));
        w.line(&format!("original.value.len = {n};"));
    }
    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line(&format!("assert({pfx}_{type_name}_encode(&enc, &original) == 0);"));
    w.line("size_t enc_len = nanocbor_encoded_len(&enc);");
    w.line(&format!("{type_name}_t decoded = {{0}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line(&format!("assert({pfx}_{type_name}_decode(&dec, &decoded, NULL, NULL) == 0);"));
    w.line(&format!("printf(\"{pfx}_{type_name}_roundtrip: PASS\\n\");"));
    w.dedent();
    w.line("}");
}

fn emit_c_array_test(w: &mut IndentWriter, a: &ArrayDef, pfx: &str, _opts: &CodegenOptions) {
    let type_name = to_snake_case(&a.name);
    w.line(&format!("static void test_{pfx}_{type_name}_roundtrip(void) {{"));
    w.indent();
    w.line(&format!("{type_name}_t original = {{0}};"));
    w.line("original.count = 0;");
    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line(&format!("assert({pfx}_{type_name}_encode(&enc, &original) == 0);"));
    w.line("size_t enc_len = nanocbor_encoded_len(&enc);");
    w.line(&format!("{type_name}_t decoded = {{0}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line(&format!("assert({pfx}_{type_name}_decode(&dec, &decoded, NULL, NULL) == 0);"));
    w.line("assert(decoded.count == original.count);");
    w.line(&format!("printf(\"{pfx}_{type_name}_roundtrip: PASS\\n\");"));
    w.dedent();
    w.line("}");
}

fn emit_c_enum_test(w: &mut IndentWriter, e: &EnumDef, pfx: &str, _opts: &CodegenOptions) {
    let type_name = to_snake_case(&e.name);
    w.line(&format!("static void test_{pfx}_{type_name}_roundtrip(void) {{"));
    w.indent();
    if let Some(v) = e.variants.first() {
        let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
        w.line(&format!("{type_name}_t original = {{ .tag = {vconst} }};"));
    } else {
        w.line(&format!("{type_name}_t original = {{0}};"));
    }
    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line(&format!("assert({pfx}_{type_name}_encode(&enc, &original) == 0);"));
    w.line("size_t enc_len = nanocbor_encoded_len(&enc);");
    w.line(&format!("{type_name}_t decoded = {{0}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line(&format!("assert({pfx}_{type_name}_decode(&dec, &decoded, NULL, NULL) == 0);"));
    w.line("assert(decoded.tag == original.tag);");
    w.line(&format!("printf(\"{pfx}_{type_name}_roundtrip: PASS\\n\");"));
    w.dedent();
    w.line("}");
}

// ── C type helpers ────────────────────────────────────────────────────────────

fn c_field_type(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    match occ {
        Occurrence::ZeroOrMore { capacity } | Occurrence::OneOrMore { capacity }
        | Occurrence::Bounded { capacity, .. } => {
            let cap  = capacity_value(capacity, opts.max_array);
            let base = typeref_to_c(ty, opts);
            format!("{base} items[{cap}]; size_t count")
        }
        _ => typeref_to_c(ty, opts),
    }
}

fn typeref_to_c(ty: &TypeRef, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p)    => primitive_to_c(p).to_owned(),
        TypeRef::Named(n)        => format!("{}_t", to_snake_case(n)),
        TypeRef::Tagged(_, inner) => typeref_to_c(inner, opts),
        TypeRef::Choice(cs)      => cs.first()
            .map(|c| typeref_to_c(c, opts))
            .unwrap_or_else(|| "void*".into()),
    }
}

/// If `type_name` resolves to a `tstr .size N` alias, return `Some(N)`.
fn tstr_size_constraint_for(type_name: &str, module: &IrModule) -> Option<usize> {
    match module.types.get(type_name)? {
        TypeDef::Alias(a) if matches!(&a.ty, TypeRef::Primitive(Primitive::Tstr)) => {
            a.constraints.iter().find_map(|c| match c {
                Constraint::SizeExact(n) => Some(*n),
                Constraint::SizeRange { min: Some(n), .. } => Some(*n),
                _ => None,
            })
        }
        _ => None,
    }
}

fn c_default_value(ty: &TypeRef, _opts: &CodegenOptions) -> Option<String> {
    match ty {
        TypeRef::Primitive(Primitive::Uint) => Some("0U".into()),
        TypeRef::Primitive(Primitive::Int)  => Some("0".into()),
        TypeRef::Primitive(Primitive::Bool) => Some("false".into()),
        TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) => Some("0.0f".into()),
        TypeRef::Primitive(Primitive::Float64 | Primitive::Float)   => Some("0.0".into()),
        _ => None,
    }
}

fn emit_c_doc(w: &mut IndentWriter, doc: Option<&str>) {
    if let Some(d) = doc {
        w.line(&format!("/* {} */", d.replace("*/", "*/")));
    }
}
