/// C backend for cddlc.
///
/// Emits a C library crate:
///   <module>-cbor/
///     CMakeLists.txt
///     include/<module>.h      ← type declarations + callback API
///     src/<module>.c          ← encode/decode implementations
///     test/test_roundtrip.c   ← roundtrip tests (Unity framework)

use cddlc_codegen::{
    capacity_value, constraint_to_c_check, primitive_to_c,
    to_screaming_snake, to_snake_case,
    Backend, CodegenError, CodegenOptions, CodegenOutput, GeneratedFile,
    IndentWriter,
};
use cddlc_ir::{
    AliasDef, ArrayDef, Capacity, Constraint, EnumDef,
    IrModule, Occurrence, Primitive, StructDef, TypeDef, TypeRef,
};

pub struct CBackend;

impl Backend for CBackend {
    fn language_name(&self) -> &str { "C" }
    fn file_extension(&self) -> &str { "h" }

    fn generate(
        &self,
        module: &IrModule,
        opts:   &CodegenOptions,
    ) -> Result<CodegenOutput, CodegenError> {
        let name      = module.name.as_str();
        let fmt_tag   = if opts.is_json() { "json" } else { "cbor" };
        let crate_dir = format!("{name}-{fmt_tag}");

        if opts.is_json() {
            return Ok(CodegenOutput {
                files: vec![
                    GeneratedFile {
                        path:    format!("{crate_dir}/CMakeLists.txt"),
                        content: emit_cmake_json(name, opts),
                    },
                    GeneratedFile {
                        path:    format!("{crate_dir}/include/{name}.h"),
                        content: emit_header_json(module, opts),
                    },
                    GeneratedFile {
                        path:    format!("{crate_dir}/src/{name}.c"),
                        content: emit_source_json(module, opts),
                    },
                    GeneratedFile {
                        path:    format!("{crate_dir}/test/test_roundtrip.c"),
                        content: emit_tests_json(module, opts),
                    },
                ],
            });
        }

        Ok(CodegenOutput {
            files: vec![
                GeneratedFile {
                    path:    format!("{crate_dir}/CMakeLists.txt"),
                    content: emit_cmake(name, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/include/{name}.h"),
                    content: emit_header(module, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/include/nanocbor_compat.h"),
                    content: NANOCBOR_MACOS_COMPAT_H.to_string(),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/src/{name}.c"),
                    content: emit_source(module, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/test/test_roundtrip.c"),
                    content: emit_tests(module, opts),
                },
            ],
        })
    }
}

// ── macOS compat header ───────────────────────────────────────────────────────

/// Compatibility shim for nanocbor on macOS.
///
/// nanocbor/config.h defaults to Linux's `endian.h` and uses `be64toh`,
/// `htobe64`, etc. which do not exist on macOS.  This header overrides those
/// macros to use the macOS `<libkern/OSByteOrder.h>` equivalents.
const NANOCBOR_MACOS_COMPAT_H: &str = r#"/* @generated by cddlc — do not edit manually */
/* macOS compatibility shim for nanocbor byte-order functions */
#pragma once
#include <libkern/OSByteOrder.h>
/* Override nanocbor/config.h default so it does not request Linux endian.h */
#define NANOCBOR_BYTEORDER_HEADER <libkern/OSByteOrder.h>
/* Map Linux byte-order functions to their macOS equivalents */
#define be16toh(x) OSSwapBigToHostInt16(x)
#define be32toh(x) OSSwapBigToHostInt32(x)
#define be64toh(x) OSSwapBigToHostInt64(x)
#define htobe16(x) OSSwapHostToBigInt16(x)
#define htobe32(x) OSSwapHostToBigInt32(x)
#define htobe64(x) OSSwapHostToBigInt64(x)
#define le16toh(x) OSSwapLittleToHostInt16(x)
#define le32toh(x) OSSwapLittleToHostInt32(x)
#define le64toh(x) OSSwapLittleToHostInt64(x)
#define htole16(x) OSSwapHostToLittleInt16(x)
#define htole32(x) OSSwapHostToLittleInt32(x)
#define htole64(x) OSSwapHostToLittleInt64(x)
"#;

// ── CMakeLists.txt ────────────────────────────────────────────────────────────

fn emit_cmake(name: &str, _opts: &CodegenOptions) -> String {
    format!(r#"# @generated by cddlc — do not edit manually
cmake_minimum_required(VERSION 3.16)
project({name}_cbor C)

set(CMAKE_C_STANDARD 11)

# macOS: force-include compat shim for nanocbor's Linux byte-order functions.
# Must be set before FetchContent_MakeAvailable so it applies to nanocbor's
# own compilation units as well.
if(APPLE)
    set(_nanocbor_compat "${{CMAKE_CURRENT_SOURCE_DIR}}/include/nanocbor_compat.h")
    add_compile_options(-include "${{_nanocbor_compat}}")
endif()

include(FetchContent)
FetchContent_Declare(nanocbor
    GIT_REPOSITORY https://github.com/bergzand/NanoCBOR.git
    GIT_TAG        master
)
set(NANOCBOR_BUILD_TESTS OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(nanocbor)

file(GLOB NANOCBOR_SOURCES "${{nanocbor_SOURCE_DIR}}/src/*.c")

add_library({name}_cbor
    src/{name}.c
    ${{NANOCBOR_SOURCES}}
)
target_include_directories({name}_cbor PUBLIC include ${{nanocbor_SOURCE_DIR}}/include)

# Tests (requires Unity test framework)
enable_testing()
add_executable(test_roundtrip test/test_roundtrip.c)
target_link_libraries(test_roundtrip {name}_cbor)
add_test(NAME roundtrip COMMAND test_roundtrip)
"#)
}

// ── Header file ───────────────────────────────────────────────────────────────

fn emit_header(module: &IrModule, opts: &CodegenOptions) -> String {
    let name    = module.name.as_str();
    let guard   = format!("{}_H", name.to_uppercase().replace('-', "_"));
    let mut w   = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line(&format!("#ifndef {guard}"));
    w.line(&format!("#define {guard}"));
    w.blank();
    w.line("#include <stdint.h>");
    w.line("#include <stddef.h>");
    w.line("#include <stdbool.h>");
    w.line("#include <nanocbor/nanocbor.h>");
    w.blank();

    // ── Common types ──────────────────────────────────────────────────────────
    w.line("/* Zero-copy string slice (points into decode buffer) */");
    w.line("typedef struct { const char *ptr; size_t len; } cbor_str_t;");
    w.blank();
    w.line("/* Zero-copy byte slice */");
    w.line("typedef struct { const uint8_t *ptr; size_t len; } cbor_bytes_t;");
    w.line("typedef cbor_bytes_t cbor_slice_t;");
    w.line("typedef cbor_bytes_t cbor_any_t;");
    w.blank();

    // ── Error codes ───────────────────────────────────────────────────────────
    w.line("typedef enum {");
    w.indent();
    w.line(&format!("{}_OK = 0,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_TYPE,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_VALUE,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_MISSING,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_OVERFLOW,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_UTF8,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_UNKNOWN_FIELD,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_TAG,", to_screaming_snake(name)));
    w.line(&format!("{}_ERR_VALIDATION,", to_screaming_snake(name)));
    w.dedent();
    w.line(&format!("}} {}_err_t;", to_snake_case(name)));
    w.blank();

    // ── Field error ───────────────────────────────────────────────────────────
    w.line("typedef struct {");
    w.indent();
    w.line(&format!("{}_err_t  code;", to_snake_case(name)));
    w.line("const char     *field;");
    w.line("size_t          index;");
    w.dedent();
    w.line(&format!("}} {}_field_err_t;", to_snake_case(name)));
    w.blank();

    // ── Callbacks ─────────────────────────────────────────────────────────────
    w.line("/* Callbacks provided by the caller */");
    w.line("typedef struct {");
    w.indent();
    w.line(&format!(
        "void (*on_error)(void *ctx, {}_field_err_t err);",
        to_snake_case(name)
    ));
    w.line("void (*on_unknown_field)(void *ctx, cbor_str_t key);");
    w.dedent();
    w.line(&format!("}} {}_callbacks_t;", to_snake_case(name)));
    w.blank();

    // ── Type declarations ─────────────────────────────────────────────────────
    for (_, def) in &module.types {
        emit_type_decl_h(&mut w, def, name, opts);
        w.blank();
    }

    // ── Function declarations ─────────────────────────────────────────────────
    w.line("/* Encode/decode function declarations */");
    for (_, def) in &module.types {
        emit_fn_decls(&mut w, def, name, opts);
    }
    w.blank();

    w.line(&format!("#endif /* {guard} */"));
    w.finish()
}

fn emit_type_decl_h(w: &mut IndentWriter, def: &TypeDef, _mod_name: &str, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct_decl(w, s, opts),
        TypeDef::Enum(e)   => emit_enum_decl(w, e, opts),
        TypeDef::Array(a)  => emit_array_decl(w, a, opts),
        TypeDef::Alias(a)  => emit_alias_decl(w, a, opts),
        TypeDef::Map(_)    => {}
    }
}

fn emit_struct_decl(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    emit_c_doc(w, s.doc.as_deref());
    let type_name = to_snake_case(&s.name);
    w.line(&format!("typedef struct {{"));
    w.indent();
    for f in &s.fields {
        let ty_str = c_field_type(&f.ty, &f.occurrence, opts);
        let fname  = to_snake_case(&f.name);
        w.line(&format!("{ty_str} {fname};"));
        // bool present flag for optional fields
        if matches!(f.occurrence, Occurrence::Optional) {
            w.line(&format!("bool {fname}_present;"));
        }
    }
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_enum_decl(w: &mut IndentWriter, e: &EnumDef, _opts: &CodegenOptions) {
    emit_c_doc(w, e.doc.as_deref());
    let type_name = to_snake_case(&e.name);

    // Tag enum
    w.line("typedef enum {");
    w.indent();
    for (i, v) in e.variants.iter().enumerate() {
        let vname = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
        if i == e.variants.len() - 1 {
            w.line(&format!("{vname}"));
        } else {
            w.line(&format!("{vname},"));
        }
    }
    w.dedent();
    w.line(&format!("}} {type_name}_tag_t;"));
    w.blank();

    // Union struct
    w.line(&format!("typedef struct {{"));
    w.indent();
    w.line(&format!("{type_name}_tag_t tag;"));
    w.line("union {");
    w.indent();
    for v in &e.variants {
        let vname = to_snake_case(&v.name);
        match &v.ty {
            TypeRef::Primitive(Primitive::Null) => {}
            TypeRef::Primitive(p) => {
                w.line(&format!("{} {};", primitive_to_c(p), vname));
            }
            TypeRef::Named(n) => {
                w.line(&format!("{}_t {};", to_snake_case(n), vname));
            }
            _ => {}
        }
    }
    w.dedent();
    w.line("} value;");
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_array_decl(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    emit_c_doc(w, a.doc.as_deref());
    let type_name = to_snake_case(&a.name);
    let elem_ty   = typeref_to_c(&a.element, opts);
    let cap       = capacity_value(
        a.occurrence.capacity().unwrap_or(&Capacity::Bounded(opts.max_array)),
        opts.max_array,
    );
    w.line(&format!("typedef struct {{"));
    w.indent();
    w.line(&format!("{elem_ty} items[{cap}];"));
    w.line("size_t count;");
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_alias_decl(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    emit_c_doc(w, a.doc.as_deref());
    let type_name = to_snake_case(&a.name);
    if a.tagged.is_some() || !a.constraints.is_empty() {
        // Newtype struct for tagged/constrained aliases
        let inner = typeref_to_c(&a.ty, opts);
        w.line(&format!("typedef struct {{ {inner} value; }} {type_name}_t;"));
    } else {
        let inner = typeref_to_c(&a.ty, opts);
        w.line(&format!("typedef {inner} {type_name}_t;"));
    }
}

fn emit_fn_decls(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, _opts: &CodegenOptions) {
    let type_name = to_snake_case(def.name());
    let pfx       = to_snake_case(mod_name);

    w.line(&format!(
        "int {pfx}_{type_name}_encode(nanocbor_encoder_t *enc, const {type_name}_t *val);"
    ));
    w.line(&format!(
        "int {pfx}_{type_name}_decode(nanocbor_value_t *dec, {type_name}_t *out, \
         const {pfx}_callbacks_t *cb, void *ctx);"
    ));
}

// ── Source file ───────────────────────────────────────────────────────────────

fn emit_source(module: &IrModule, opts: &CodegenOptions) -> String {
    let name  = module.name.as_str();
    let mut w = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line(&format!("#include \"{name}.h\""));
    w.line("#include <string.h>");
    w.blank();

    for (_, def) in &module.types {
        w.blank();
        emit_encode_fn(&mut w, def, name, opts);
        w.blank();
        emit_decode_fn(&mut w, def, name, opts);
    }

    w.finish()
}

fn emit_encode_fn(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, opts: &CodegenOptions) {
    let type_name = to_snake_case(def.name());
    let pfx       = to_snake_case(mod_name);

    w.line(&format!(
        "int {pfx}_{type_name}_encode(nanocbor_encoder_t *enc, const {type_name}_t *val) {{"
    ));
    w.indent();

    match def {
        TypeDef::Struct(s) => {
            // Emit tag if present
            if let Some(tag) = s.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            // dCBOR: sort keys — for now emit in definition order
            let fields: Vec<_> = if opts.dcbor {
                let mut fs: Vec<_> = s.fields.iter().collect();
                fs.sort_by(|a, b| a.name.cmp(&b.name));
                fs
            } else {
                s.fields.iter().collect()
            };
            // Compute map count: required fields always present; optional only when _present flag set
            let req_count = fields.iter().filter(|f| !matches!(f.occurrence, Occurrence::Optional)).count();
            let opt_fields: Vec<_> = fields.iter().filter(|f| matches!(f.occurrence, Occurrence::Optional)).collect();
            if opt_fields.is_empty() {
                w.line(&format!("nanocbor_fmt_map(enc, {req_count}u);"));
            } else {
                let opt_sum: String = opt_fields.iter().map(|f| {
                    let fname = to_snake_case(&f.name);
                    format!("(val->{fname}_present ? 1u : 0u)")
                }).collect::<Vec<_>>().join(" + ");
                w.line(&format!("nanocbor_fmt_map(enc, {req_count}u + {opt_sum});"));
            }
            for f in &fields {
                let fname = to_snake_case(&f.name);
                if matches!(f.occurrence, Occurrence::Optional) {
                    w.line(&format!("if (val->{fname}_present) {{"));
                    w.indent();
                    w.line(&format!("nanocbor_put_tstr(enc, {:?});", f.name.as_str()));
                    emit_c_encode_field(w, &f.ty, &format!("val->{fname}"), &f.occurrence, mod_name, opts);
                    w.dedent();
                    w.line("}");
                } else {
                    w.line(&format!("nanocbor_put_tstr(enc, {:?});", f.name.as_str()));
                    emit_c_encode_field(w, &f.ty, &format!("val->{fname}"), &f.occurrence, mod_name, opts);
                }
            }
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Enum(e) => {
            if let Some(tag) = e.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            w.line(&format!("switch (val->tag) {{"));
            for v in &e.variants {
                let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
                let vname  = to_snake_case(&v.name);
                w.line(&format!("case {vconst}:"));
                w.indent();
                match &v.ty {
                    TypeRef::Primitive(Primitive::Tstr) => {
                        let s = v.name.to_lowercase().replace('_', "-");
                        w.line(&format!("nanocbor_put_tstr(enc, {:?});", s));
                    }
                    TypeRef::Primitive(Primitive::Uint) =>
                        w.line(&format!("nanocbor_fmt_uint(enc, val->value.{vname});")),
                    TypeRef::Primitive(Primitive::Int) =>
                        w.line(&format!("nanocbor_fmt_int(enc, val->value.{vname});")),
                    TypeRef::Primitive(Primitive::Bool) =>
                        w.line(&format!("nanocbor_fmt_bool(enc, val->value.{vname});")),
                    TypeRef::Primitive(Primitive::Null) =>
                        w.line("nanocbor_fmt_null(enc);"),
                    TypeRef::Named(n) => {
                        let np = to_snake_case(mod_name);
                        let tn = to_snake_case(n);
                        w.line(&format!("{np}_{tn}_encode(enc, &val->value.{vname});"));
                    }
                    _ => w.line("nanocbor_fmt_null(enc);"),
                }
                w.line("break;");
                w.dedent();
            }
            w.line("}");
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Array(a) => {
            if let Some(tag) = a.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            w.line("nanocbor_fmt_array(enc, val->count);");
            w.line("for (size_t i = 0; i < val->count; i++) {");
            w.indent();
            emit_c_encode_field(w, &a.element, "val->items[i]", &Occurrence::Required, mod_name, opts);
            w.dedent();
            w.line("}");
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Alias(a) => {
            if let Some(tag) = a.tagged {
                w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            }
            let inner_expr = if a.tagged.is_some() || !a.constraints.is_empty() {
                "val->value".to_string()
            } else {
                "(*val)".to_string()
            };
            emit_c_encode_field(w, &a.ty, &inner_expr, &Occurrence::Required, mod_name, opts);
            w.line("return NANOCBOR_OK;");
        }
        TypeDef::Map(_) => {
            w.line("return NANOCBOR_OK;");
        }
    }

    w.dedent();
    w.line("}");
}

fn emit_c_encode_field(
    w:        &mut IndentWriter,
    ty:       &TypeRef,
    expr:     &str,
    occ:      &Occurrence,
    mod_name: &str,
    opts:     &CodegenOptions,
) {
    match ty {
        TypeRef::Primitive(p) => {
            let call = c_encode_call(p, expr);
            w.line(&format!("{call};"));
        }
        TypeRef::Named(n) => {
            let pfx = to_snake_case(mod_name);
            let tn  = to_snake_case(n);
            w.line(&format!("{pfx}_{tn}_encode(enc, &{expr});"));
        }
        TypeRef::Tagged(tag, inner) => {
            w.line(&format!("nanocbor_fmt_tag(enc, {});", tag.0));
            emit_c_encode_field(w, inner, expr, occ, mod_name, opts);
        }
        TypeRef::Choice(_) => {
            w.line("/* choice encode */");
        }
    }
}

fn c_encode_call(p: &Primitive, expr: &str) -> String {
    match p {
        Primitive::Bool               => format!("nanocbor_fmt_bool(enc, {expr})"),
        Primitive::Null | Primitive::Undefined => "nanocbor_fmt_null(enc)".into(),
        Primitive::Uint               => format!("nanocbor_fmt_uint(enc, {expr})"),
        Primitive::Int                => format!("nanocbor_fmt_int(enc, {expr})"),
        Primitive::Float32            => format!("nanocbor_fmt_float(enc, {expr})"),
        Primitive::Float64 | Primitive::Float => format!("nanocbor_fmt_double(enc, {expr})"),
        Primitive::Float16            => format!("nanocbor_fmt_float(enc, {expr})"),
        Primitive::Bstr | Primitive::Any =>
            format!("nanocbor_put_bstr(enc, {expr}.ptr, {expr}.len)"),
        Primitive::Tstr               =>
            format!("nanocbor_put_tstrn(enc, {expr}.ptr, {expr}.len)"),
    }
}

fn emit_decode_fn(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, opts: &CodegenOptions) {
    let type_name = to_snake_case(def.name());
    let pfx       = to_snake_case(mod_name);
    let pfx_upper = to_screaming_snake(mod_name);

    w.line(&format!(
        "int {pfx}_{type_name}_decode(nanocbor_value_t *dec, {type_name}_t *out, \
         const {pfx}_callbacks_t *cb, void *ctx) {{"
    ));
    w.indent();
    w.line("int rc;");
    w.line(&format!("(void)cb; (void)ctx;"));

    match def {
        TypeDef::Struct(s) => {
            // Tag verification
            if let Some(tag) = s.tagged {
                w.line("{");
                w.indent();
                w.line("uint32_t tag;");
                w.line("if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("if (tag != {}) {{", tag.0));
                w.indent();
                w.line(&format!(
                    "if (cb && cb->on_error) cb->on_error(ctx, ({pfx}_field_err_t){{{pfx_upper}_ERR_TAG, \"{type_name}\", 0}});"
                ));
                w.line("return -1;");
                w.dedent();
                w.line("}");
                w.dedent();
                w.line("}");
            }

            w.line("nanocbor_value_t map;");
            w.line("if (nanocbor_enter_map(dec, &map) < 0) return -1;");
            w.blank();

            // Zero-init the output
            w.line(&format!("memset(out, 0, sizeof({type_name}_t));"));
            w.blank();

            w.line("while (!nanocbor_at_end(&map)) {");
            w.indent();
            w.line("const uint8_t *key_ptr; size_t key_len;");
            w.line("if (nanocbor_get_tstr(&map, &key_ptr, &key_len) < 0) return -1;");
            w.blank();

            for f in &s.fields {
                let fname  = to_snake_case(&f.name);
                let fkey   = f.name.as_str();
                w.line(&format!(
                    "if (key_len == {} && memcmp(key_ptr, {:?}, {}) == 0) {{",
                    fkey.len(), fkey, fkey.len()
                ));
                w.indent();
                emit_c_decode_field(w, &f.ty, &format!("out->{fname}"), &f.constraints, &fname, &pfx, &pfx_upper, "&map", opts);
                if matches!(f.occurrence, Occurrence::Optional) {
                    w.line(&format!("out->{fname}_present = true;"));
                }
                w.dedent();
                w.line("} else");
            }
            // Unknown field handler
            w.line("{");
            w.indent();
            w.line("if (cb && cb->on_unknown_field) {");
            w.indent();
            w.line("cbor_str_t uk = { (const char*)key_ptr, key_len };");
            w.line("cb->on_unknown_field(ctx, uk);");
            w.dedent();
            w.line("}");
            w.line("nanocbor_skip(&map);");
            w.dedent();
            w.line("}");

            w.dedent();
            w.line("}"); // while

            // Check required fields
            for f in &s.fields {
                if matches!(f.occurrence, Occurrence::Required) {
                    let fname = to_snake_case(&f.name);
                    // Simple check: for numeric fields, can't easily detect missing
                    // For pointer fields, check for NULL
                    match &f.ty {
                        TypeRef::Primitive(Primitive::Tstr | Primitive::Bstr) => {
                            w.line(&format!("if (!out->{fname}.ptr) {{"));
                            w.indent();
                            w.line(&format!(
                                "if (cb && cb->on_error) cb->on_error(ctx, ({pfx}_field_err_t){{{pfx_upper}_ERR_MISSING, {:?}, 0}});",
                                f.name.as_str()
                            ));
                            w.line("return -1;");
                            w.dedent();
                            w.line("}");
                        }
                        _ => {}
                    }
                }
            }

            w.line("nanocbor_leave_container(dec, &map);");
            w.line("return NANOCBOR_OK;");
        }

        TypeDef::Enum(e) => {
            if let Some(tag) = e.tagged {
                w.line("{");
                w.indent();
                w.line("uint32_t tag;");
                w.line("if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("if (tag != {}) return -1;", tag.0));
                w.dedent();
                w.line("}");
            }

            // Peek at type
            w.line("uint8_t major = nanocbor_get_type(dec);");
            w.line("if (major == NANOCBOR_TYPE_TSTR) {");
            w.indent();
            w.line("const uint8_t *s; size_t slen;");
            w.line("if (nanocbor_get_tstr(dec, &s, &slen) < 0) return -1;");
            for v in &e.variants {
                if matches!(&v.ty, TypeRef::Primitive(Primitive::Tstr)) {
                    let cddl_str = v.name.to_lowercase().replace('_', "-");
                    let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
                    w.line(&format!(
                        "if (slen == {} && memcmp(s, {:?}, {}) == 0) {{ out->tag = {vconst}; return NANOCBOR_OK; }}",
                        cddl_str.len(), cddl_str, cddl_str.len()
                    ));
                }
            }
            w.line("return -1; /* unknown variant */");
            w.dedent();
            w.line("} else if (major == NANOCBOR_TYPE_UINT || major == NANOCBOR_TYPE_NINT) {");
            w.indent();
            for v in &e.variants {
                if matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)) {
                    let vname  = to_snake_case(&v.name);
                    let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
                    w.line(&format!("if (nanocbor_get_int32(dec, (int32_t*)&out->value.{vname}) < 0) return -1;"));
                    w.line(&format!("out->tag = {vconst};"));
                    w.line("return NANOCBOR_OK;");
                    break;
                }
            }
            w.line("return -1;");
            w.dedent();
            w.line("}");
            w.line("return -1;");
        }

        TypeDef::Array(a) => {
            if let Some(tag) = a.tagged {
                w.line("{");
                w.indent();
                w.line("uint32_t tag;");
                w.line("if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("if (tag != {}) return -1;", tag.0));
                w.dedent();
                w.line("}");
            }
            let cap = capacity_value(
                a.occurrence.capacity().unwrap_or(&Capacity::Bounded(opts.max_array)),
                opts.max_array,
            );
            w.line("nanocbor_value_t arr;");
            w.line("if (nanocbor_enter_array(dec, &arr) < 0) return -1;");
            w.line("out->count = 0;");
            w.line(&format!("while (!nanocbor_at_end(&arr) && out->count < {cap}) {{"));
            w.indent();
            emit_c_decode_field(w, &a.element, "out->items[out->count]", &[], "item", &pfx, &pfx_upper, "&arr", opts);
            w.line("out->count++;");
            w.dedent();
            w.line("}");
            w.line("nanocbor_leave_container(dec, &arr);");
            w.line("return NANOCBOR_OK;");
        }

        TypeDef::Alias(a) => {
            if let Some(tag) = a.tagged {
                w.line("{");
                w.indent();
                w.line("uint32_t tag;");
                w.line("if (nanocbor_get_tag(dec, &tag) < 0) return -1;");
                w.line(&format!("if (tag != {}) {{", tag.0));
                w.indent();
                w.line(&format!(
                    "if (cb && cb->on_error) cb->on_error(ctx, ({pfx}_field_err_t){{{pfx_upper}_ERR_TAG, \"{type_name}\", 0}});"
                ));
                w.line("return -1;");
                w.dedent();
                w.line("}");
                w.dedent();
                w.line("}");
            }
            let dest = if a.tagged.is_some() || !a.constraints.is_empty() {
                "out->value".to_string()
            } else {
                "(*out)".to_string()
            };
            emit_c_decode_field(w, &a.ty, &dest, &a.constraints, &type_name, &pfx, &pfx_upper, "dec", opts);
            w.line("return NANOCBOR_OK;");
        }

        TypeDef::Map(_) => {
            w.line("return NANOCBOR_OK;");
        }
    }

    w.dedent();
    w.line("}");
}

fn emit_c_decode_field(
    w:           &mut IndentWriter,
    ty:          &TypeRef,
    dest:        &str,
    constraints: &[Constraint],
    field_name:  &str,
    pfx:         &str,
    pfx_upper:   &str,
    dec_expr:    &str,
    opts:        &CodegenOptions,
) {
    match ty {
        TypeRef::Primitive(p) => {
            let call = c_decode_call_expr(p, dest, dec_expr);
            w.line(&format!("if ({call} < 0) return -1;"));

            // Inline validation
            for c in constraints {
                if let Some(check) = c_constraint_check(c, dest, p) {
                    w.line(&format!("if (!({check})) {{"));
                    w.indent();
                    w.line(&format!(
                        "if (cb && cb->on_error) cb->on_error(ctx, ({pfx}_field_err_t){{{pfx_upper}_ERR_VALIDATION, {:?}, 0}});",
                        field_name
                    ));
                    w.line("return -1;");
                    w.dedent();
                    w.line("}");
                }
            }
        }
        TypeRef::Named(n) => {
            let tn = to_snake_case(n);
            w.line(&format!("if ({pfx}_{tn}_decode({dec_expr}, &{dest}, cb, ctx) < 0) return -1;"));
        }
        TypeRef::Tagged(tag, inner) => {
            w.line("{");
            w.indent();
            w.line("uint32_t tag;");
            w.line(&format!("if (nanocbor_get_tag({dec_expr}, &tag) < 0) return -1;"));
            w.line(&format!("if (tag != {}) return -1;", tag.0));
            emit_c_decode_field(w, inner, dest, constraints, field_name, pfx, pfx_upper, dec_expr, opts);
            w.dedent();
            w.line("}");
        }
        TypeRef::Choice(_) => {
            w.line(&format!("nanocbor_skip({dec_expr}); /* choice — skip */"));
        }
    }
}

/// Type-aware constraint check for C.
///
/// For string/byte primitives, `.size` checks the `.len` field.
/// For integer primitives, `.size N` checks that the value fits in N bytes
/// (e.g., `.size 4` on a uint → `val <= 0xFFFFFFFFU`).
fn c_constraint_check(c: &Constraint, val_expr: &str, p: &Primitive) -> Option<String> {
    match c {
        Constraint::SizeExact(n) => match p {
            Primitive::Uint => {
                let max = uint_max_for_bytes(*n)?;
                Some(format!("{val_expr} <= {max}"))
            }
            Primitive::Int => {
                let (lo, hi) = int_range_for_bytes(*n)?;
                Some(format!("{val_expr} >= {lo} && {val_expr} <= {hi}"))
            }
            _ => constraint_to_c_check(c, val_expr),
        },
        Constraint::SizeRange { .. } => match p {
            Primitive::Uint | Primitive::Int => None, // uncommon; skip
            _ => constraint_to_c_check(c, val_expr),
        },
        _ => constraint_to_c_check(c, val_expr),
    }
}

fn uint_max_for_bytes(n: usize) -> Option<String> {
    match n {
        1 => Some("0xFFU".into()),
        2 => Some("0xFFFFU".into()),
        4 => Some("0xFFFFFFFFU".into()),
        8 => None, // uint64 always fits
        _ => None,
    }
}

fn int_range_for_bytes(n: usize) -> Option<(i64, i64)> {
    match n {
        1 => Some((-128, 127)),
        2 => Some((-32768, 32767)),
        4 => Some((-2147483648, 2147483647)),
        8 => None,
        _ => None,
    }
}

fn c_decode_call_expr(p: &Primitive, dest: &str, dec_expr: &str) -> String {
    match p {
        Primitive::Bool =>
            format!("nanocbor_get_bool({dec_expr}, &{dest})"),
        Primitive::Null | Primitive::Undefined =>
            format!("nanocbor_get_null({dec_expr})"),
        Primitive::Uint =>
            format!("nanocbor_get_uint64({dec_expr}, &{dest})"),
        Primitive::Int =>
            format!("nanocbor_get_int64({dec_expr}, &{dest})"),
        Primitive::Float32 | Primitive::Float16 =>
            format!("nanocbor_get_float({dec_expr}, &{dest})"),
        Primitive::Float64 | Primitive::Float =>
            format!("nanocbor_get_double({dec_expr}, &{dest})"),
        Primitive::Tstr =>
            format!("(nanocbor_get_tstr({dec_expr}, (const uint8_t**)&{dest}.ptr, &{dest}.len))"),
        Primitive::Bstr | Primitive::Any =>
            format!("nanocbor_get_bstr({dec_expr}, &{dest}.ptr, &{dest}.len)"),
    }
}

// ── Test file ─────────────────────────────────────────────────────────────────

fn emit_tests(module: &IrModule, opts: &CodegenOptions) -> String {
    let name  = module.name.as_str();
    let pfx   = to_snake_case(name);
    let mut w = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line("/* Roundtrip encode/decode tests */");
    w.line(&format!("#include \"{name}.h\""));
    w.line("#include <assert.h>");
    w.line("#include <string.h>");
    w.line("#include <stdio.h>");
    w.blank();
    w.line("static uint8_t buf[1024];");
    w.blank();

    for (_, def) in &module.types {
        match def {
            TypeDef::Struct(s) => emit_c_struct_test(&mut w, s, &pfx, module, opts),
            TypeDef::Alias(a)  => emit_c_alias_test(&mut w, a, &pfx, opts),
            TypeDef::Array(a)  => emit_c_array_test(&mut w, a, &pfx, opts),
            TypeDef::Enum(e)   => emit_c_enum_test(&mut w, e, &pfx, opts),
            TypeDef::Map(_)    => {}
        }
        w.blank();
    }

    // main
    w.line("int main(void) {");
    w.indent();
    for (_, def) in &module.types {
        let type_name = to_snake_case(def.name());
        w.line(&format!("test_{pfx}_{type_name}_roundtrip();"));
    }
    w.line("printf(\"All roundtrip tests passed.\\n\");");
    w.line("return 0;");
    w.dedent();
    w.line("}");

    w.finish()
}

fn emit_c_struct_test(w: &mut IndentWriter, s: &StructDef, pfx: &str, module: &IrModule, opts: &CodegenOptions) {
    let type_name = to_snake_case(&s.name);
    w.line(&format!("static void test_{pfx}_{type_name}_roundtrip(void) {{"));
    w.indent();

    // Static buffers for any size-constrained tstr named fields, and for inline Tstr/Bstr/Any fields
    for f in &s.fields {
        if matches!(f.occurrence, Occurrence::Optional) { continue; }
        let fname = to_snake_case(&f.name);
        if let TypeRef::Named(n) = &f.ty {
            if let Some(n) = tstr_size_constraint_for(n, module) {
                let s_lit: String = "a".repeat(n);
                w.line(&format!("static const char _{fname}_data[{n}] = {:?};", s_lit));
            }
        }
        match effective_primitive(&f.ty) {
            Some(Primitive::Tstr) => {
                w.line(&format!("static const char _{fname}_str[] = \"hello\";"));
            }
            Some(Primitive::Bstr | Primitive::Any) => {
                w.line(&format!("static const uint8_t _{fname}_cbor[1] = {{0xf6}};"));
            }
            _ => {}
        }
    }

    // Build a zeroed instance
    w.line(&format!("{type_name}_t original = {{0}};"));

    // Fill in default values for each field
    for f in &s.fields {
        if matches!(f.occurrence, Occurrence::Optional) { continue; }
        let fname = to_snake_case(&f.name);
        if let TypeRef::Named(n) = &f.ty {
            if let Some(n) = tstr_size_constraint_for(n, module) {
                w.line(&format!("original.{fname}.value.ptr = _{fname}_data;"));
                w.line(&format!("original.{fname}.value.len = {n};"));
                continue;
            }
        }
        match effective_primitive(&f.ty) {
            Some(Primitive::Tstr) => {
                w.line(&format!("original.{fname}.ptr = _{fname}_str;"));
                w.line(&format!("original.{fname}.len = 5; /* \"hello\" */"));
                continue;
            }
            Some(Primitive::Bstr | Primitive::Any) => {
                w.line(&format!("original.{fname}.ptr = _{fname}_cbor;"));
                w.line(&format!("original.{fname}.len = 1; /* CBOR null 0xf6 */"));
                continue;
            }
            _ => {}
        }
        let val = c_default_value(&f.ty, opts);
        if let Some(v) = val {
            w.line(&format!("original.{fname} = {v};"));
        }
    }
    w.blank();

    // Encode
    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line(&format!("assert({pfx}_{type_name}_encode(&enc, &original) == 0);"));
    w.line("size_t enc_len = nanocbor_encoded_len(&enc);");
    w.blank();

    // Decode
    w.line(&format!("{type_name}_t decoded = {{0}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line(&format!("assert({pfx}_{type_name}_decode(&dec, &decoded, NULL, NULL) == 0);"));
    w.blank();

    // Assert equality for scalar fields
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        match &f.ty {
            TypeRef::Primitive(Primitive::Tstr | Primitive::Bstr | Primitive::Any) => {
                w.line(&format!("assert(original.{fname}.len == decoded.{fname}.len);"));
            }
            TypeRef::Primitive(_) => {
                w.line(&format!("assert(original.{fname} == decoded.{fname});"));
            }
            _ => {}
        }
    }

    w.line(&format!("printf(\"{pfx}_{type_name}_roundtrip: PASS\\n\");"));
    w.dedent();
    w.line("}");
}

fn emit_c_alias_test(w: &mut IndentWriter, a: &AliasDef, pfx: &str, _opts: &CodegenOptions) {
    let type_name = to_snake_case(&a.name);
    w.line(&format!("static void test_{pfx}_{type_name}_roundtrip(void) {{"));
    w.indent();

    // For size-constrained tstr aliases, initialise with a valid-length literal
    // so that the roundtrip encode→decode passes constraint validation.
    let tstr_size = a.constraints.iter().find_map(|c| match c {
        Constraint::SizeExact(n) => Some(*n),
        Constraint::SizeRange { min: Some(n), .. } => Some(*n),
        _ => None,
    }).filter(|_| matches!(&a.ty, TypeRef::Primitive(Primitive::Tstr)));

    w.line(&format!("{type_name}_t original = {{0}};"));
    if let Some(n) = tstr_size {
        let s_lit: String = "a".repeat(n);
        w.line(&format!("static const char _val_data[{n}] = {:?};", s_lit));
        w.line(&format!("original.value.ptr = _val_data;"));
        w.line(&format!("original.value.len = {n};"));
    }
    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line(&format!("assert({pfx}_{type_name}_encode(&enc, &original) == 0);"));
    w.line("size_t enc_len = nanocbor_encoded_len(&enc);");
    w.line(&format!("{type_name}_t decoded = {{0}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line(&format!("assert({pfx}_{type_name}_decode(&dec, &decoded, NULL, NULL) == 0);"));
    w.line(&format!("printf(\"{pfx}_{type_name}_roundtrip: PASS\\n\");"));
    w.dedent();
    w.line("}");
}

fn emit_c_array_test(w: &mut IndentWriter, a: &ArrayDef, pfx: &str, _opts: &CodegenOptions) {
    let type_name = to_snake_case(&a.name);
    w.line(&format!("static void test_{pfx}_{type_name}_roundtrip(void) {{"));
    w.indent();
    w.line(&format!("{type_name}_t original = {{0}};"));
    w.line("original.count = 0;");
    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line(&format!("assert({pfx}_{type_name}_encode(&enc, &original) == 0);"));
    w.line("size_t enc_len = nanocbor_encoded_len(&enc);");
    w.line(&format!("{type_name}_t decoded = {{0}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line(&format!("assert({pfx}_{type_name}_decode(&dec, &decoded, NULL, NULL) == 0);"));
    w.line("assert(decoded.count == original.count);");
    w.line(&format!("printf(\"{pfx}_{type_name}_roundtrip: PASS\\n\");"));
    w.dedent();
    w.line("}");
}

fn emit_c_enum_test(w: &mut IndentWriter, e: &EnumDef, pfx: &str, _opts: &CodegenOptions) {
    let type_name = to_snake_case(&e.name);
    w.line(&format!("static void test_{pfx}_{type_name}_roundtrip(void) {{"));
    w.indent();
    if let Some(v) = e.variants.first() {
        let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
        w.line(&format!("{type_name}_t original = {{ .tag = {vconst} }};"));
    } else {
        w.line(&format!("{type_name}_t original = {{0}};"));
    }
    w.line("nanocbor_encoder_t enc;");
    w.line("nanocbor_encoder_init(&enc, buf, sizeof(buf));");
    w.line(&format!("assert({pfx}_{type_name}_encode(&enc, &original) == 0);"));
    w.line("size_t enc_len = nanocbor_encoded_len(&enc);");
    w.line(&format!("{type_name}_t decoded = {{0}};"));
    w.line("nanocbor_value_t dec;");
    w.line("nanocbor_decoder_init(&dec, buf, enc_len);");
    w.line(&format!("assert({pfx}_{type_name}_decode(&dec, &decoded, NULL, NULL) == 0);"));
    w.line("assert(decoded.tag == original.tag);");
    w.line(&format!("printf(\"{pfx}_{type_name}_roundtrip: PASS\\n\");"));
    w.dedent();
    w.line("}");
}

// ── C type helpers ────────────────────────────────────────────────────────────

fn c_field_type(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    match occ {
        Occurrence::ZeroOrMore { capacity } | Occurrence::OneOrMore { capacity }
        | Occurrence::Bounded { capacity, .. } => {
            let cap  = capacity_value(capacity, opts.max_array);
            let base = typeref_to_c(ty, opts);
            format!("{base} items[{cap}]; size_t count")
        }
        _ => typeref_to_c(ty, opts),
    }
}

fn typeref_to_c(ty: &TypeRef, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p)    => primitive_to_c(p).to_owned(),
        TypeRef::Named(n)        => format!("{}_t", to_snake_case(n)),
        TypeRef::Tagged(_, inner) => typeref_to_c(inner, opts),
        TypeRef::Choice(cs)      => cs.first()
            .map(|c| typeref_to_c(c, opts))
            .unwrap_or_else(|| "void*".into()),
    }
}

/// Returns the first concrete Primitive in a TypeRef, following Tagged and Choice.
fn effective_primitive(ty: &TypeRef) -> Option<&Primitive> {
    match ty {
        TypeRef::Primitive(p)     => Some(p),
        TypeRef::Choice(cs)       => cs.first().and_then(|c| effective_primitive(c)),
        TypeRef::Tagged(_, inner) => effective_primitive(inner),
        _ => None,
    }
}

/// If `type_name` resolves to a `tstr .size N` alias, return `Some(N)`.
fn tstr_size_constraint_for(type_name: &str, module: &IrModule) -> Option<usize> {
    match module.types.get(type_name)? {
        TypeDef::Alias(a) if matches!(&a.ty, TypeRef::Primitive(Primitive::Tstr)) => {
            a.constraints.iter().find_map(|c| match c {
                Constraint::SizeExact(n) => Some(*n),
                Constraint::SizeRange { min: Some(n), .. } => Some(*n),
                _ => None,
            })
        }
        _ => None,
    }
}

fn c_default_value(ty: &TypeRef, _opts: &CodegenOptions) -> Option<String> {
    match ty {
        TypeRef::Primitive(Primitive::Uint) => Some("42U".into()),
        TypeRef::Primitive(Primitive::Int)  => Some("-1".into()),
        TypeRef::Primitive(Primitive::Bool) => Some("true".into()),
        TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) => Some("1.0f".into()),
        TypeRef::Primitive(Primitive::Float64 | Primitive::Float)   => Some("1.0".into()),
        _ => None,
    }
}

fn emit_c_doc(w: &mut IndentWriter, doc: Option<&str>) {
    if let Some(d) = doc {
        w.line(&format!("/* {} */", d.replace("*/", "*/")));
    }
}

// ── C JSON backend (cJSON) ────────────────────────────────────────────────────

fn emit_cmake_json(name: &str, _opts: &CodegenOptions) -> String {
    format!(r#"# @generated by cddlc — do not edit manually
cmake_minimum_required(VERSION 3.16)
project({name}_json C)

set(CMAKE_C_STANDARD 11)

include(FetchContent)
FetchContent_Declare(cjson
    GIT_REPOSITORY https://github.com/DaveGamble/cJSON.git
    GIT_TAG        master
)
set(ENABLE_CJSON_TEST   OFF CACHE BOOL "" FORCE)
set(ENABLE_CJSON_UTILS  OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS   OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(cjson)

add_library({name}_json
    src/{name}.c
)
target_include_directories({name}_json PUBLIC include ${{cjson_SOURCE_DIR}})
target_link_libraries({name}_json PRIVATE cjson)

enable_testing()
add_executable(test_roundtrip test/test_roundtrip.c)
target_link_libraries(test_roundtrip PRIVATE {name}_json cjson)
add_test(NAME roundtrip COMMAND test_roundtrip)
"#)
}

#[allow(dead_code)]
fn c_json_field_type(ty: &TypeRef, opts: &CodegenOptions) -> String {
    typeref_to_c(ty, opts)
}

// ── JSON-mode type helpers ────────────────────────────────────────────────────

fn typeref_to_c_json(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(Primitive::Tstr)                  => "json_str_t".into(),
        TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => "json_bytes_t".into(),
        TypeRef::Primitive(p)                                => primitive_to_c(p).to_owned(),
        TypeRef::Named(n)                                    => format!("{}_t", to_snake_case(n)),
        TypeRef::Tagged(_, inner)                            => typeref_to_c_json(inner),
        TypeRef::Choice(cs)                                  => cs.first()
            .map(|c| typeref_to_c_json(c))
            .unwrap_or_else(|| "json_bytes_t".into()),
    }
}

fn c_field_type_json(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    match occ {
        Occurrence::ZeroOrMore { capacity } | Occurrence::OneOrMore { capacity }
        | Occurrence::Bounded { capacity, .. } => {
            let cap  = capacity_value(capacity, opts.max_array);
            let base = typeref_to_c_json(ty);
            format!("{base} items[{cap}]; size_t count")
        }
        _ => typeref_to_c_json(ty),
    }
}

fn emit_struct_decl_json(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    emit_c_doc(w, s.doc.as_deref());
    let type_name = to_snake_case(&s.name);
    w.line("typedef struct {");
    w.indent();
    for f in &s.fields {
        let ty_str = c_field_type_json(&f.ty, &f.occurrence, opts);
        let fname  = to_snake_case(&f.name);
        w.line(&format!("{ty_str} {fname};"));
        if matches!(f.occurrence, Occurrence::Optional) {
            w.line(&format!("bool {fname}_present;"));
        }
    }
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_enum_decl_json(w: &mut IndentWriter, e: &EnumDef) {
    emit_c_doc(w, e.doc.as_deref());
    let type_name = to_snake_case(&e.name);

    w.line("typedef enum {");
    w.indent();
    for (i, v) in e.variants.iter().enumerate() {
        let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
        if i == e.variants.len() - 1 { w.line(&vconst); } else { w.line(&format!("{vconst},")); }
    }
    w.dedent();
    w.line(&format!("}} {type_name}_tag_t;"));
    w.blank();

    w.line("typedef struct {");
    w.indent();
    w.line(&format!("{type_name}_tag_t tag;"));
    w.line("union {");
    w.indent();
    for v in &e.variants {
        let vname = to_snake_case(&v.name);
        match &v.ty {
            TypeRef::Primitive(Primitive::Null)                  => {}
            TypeRef::Primitive(Primitive::Tstr)                  => { w.line(&format!("json_str_t {vname};")); }
            TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => { w.line(&format!("json_bytes_t {vname};")); }
            TypeRef::Primitive(p)                                => { w.line(&format!("{} {vname};", primitive_to_c(p))); }
            TypeRef::Named(n)                                    => { w.line(&format!("{}_t {vname};", to_snake_case(n))); }
            _ => {}
        }
    }
    w.dedent();
    w.line("} value;");
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_array_decl_json(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    emit_c_doc(w, a.doc.as_deref());
    let type_name = to_snake_case(&a.name);
    let elem_ty   = typeref_to_c_json(&a.element);
    let cap       = capacity_value(
        a.occurrence.capacity().unwrap_or(&Capacity::Bounded(opts.max_array)),
        opts.max_array,
    );
    w.line("typedef struct {");
    w.indent();
    w.line(&format!("{elem_ty} items[{cap}];"));
    w.line("size_t count;");
    w.dedent();
    w.line(&format!("}} {type_name}_t;"));
}

fn emit_alias_decl_json(w: &mut IndentWriter, a: &AliasDef) {
    emit_c_doc(w, a.doc.as_deref());
    let type_name = to_snake_case(&a.name);
    if a.tagged.is_some() || !a.constraints.is_empty() {
        let inner = typeref_to_c_json(&a.ty);
        w.line(&format!("typedef struct {{ {inner} value; }} {type_name}_t;"));
    } else {
        let inner = typeref_to_c_json(&a.ty);
        w.line(&format!("typedef {inner} {type_name}_t;"));
    }
}

fn emit_type_decl_h_json(w: &mut IndentWriter, def: &TypeDef, _mod_name: &str, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct_decl_json(w, s, opts),
        TypeDef::Enum(e)   => emit_enum_decl_json(w, e),
        TypeDef::Array(a)  => emit_array_decl_json(w, a, opts),
        TypeDef::Alias(a)  => emit_alias_decl_json(w, a),
        TypeDef::Map(_)    => {}
    }
}

fn emit_header_json(module: &IrModule, opts: &CodegenOptions) -> String {
    let name     = module.name.as_str();
    let guard    = name.to_uppercase().replace('-', "_");
    let mod_name = name.replace('-', "_");
    let mut w    = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line("/* Format: JSON (RFC 8259) */");
    w.line(&format!("#ifndef {guard}_JSON_H"));
    w.line(&format!("#define {guard}_JSON_H"));
    w.blank();
    w.line("#include <stdint.h>");
    w.line("#include <stdbool.h>");
    w.line("#include <stddef.h>");
    w.line("#include <stdlib.h>");
    w.line("#include <string.h>");
    w.line("#include \"cJSON.h\"");
    w.blank();

    // Base64url helpers declaration
    w.line("/* Base64url helpers (RFC 4648, no padding) */");
    w.line("char* cddlc_b64url_encode(const uint8_t* data, size_t len);");
    w.line("uint8_t* cddlc_b64url_decode(const char* s, size_t* out_len);");
    w.blank();

    w.line("/* JSON owned-value types */");
    w.line("typedef char json_str_t[256];");
    w.line("typedef struct { uint8_t data[512]; size_t len; } json_bytes_t;");
    w.blank();

    for (_, def) in &module.types {
        emit_type_decl_h_json(&mut w, def, &mod_name, opts);
        w.blank();
    }

    // Function declarations
    for (_, def) in &module.types {
        emit_json_fn_decls(&mut w, def, &mod_name, opts);
        w.blank();
    }

    w.line(&format!("#endif /* {guard}_JSON_H */"));
    w.finish()
}

fn emit_json_fn_decls(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, opts: &CodegenOptions) {
    let (name, ctype) = match def {
        TypeDef::Struct(s) => (s.name.as_str(), format!("{}_t", to_snake_case(&s.name))),
        TypeDef::Enum(e)   => (e.name.as_str(), format!("{}_t", to_snake_case(&e.name))),
        TypeDef::Array(a)  => (a.name.as_str(), format!("{}_t", to_snake_case(&a.name))),
        TypeDef::Alias(a)  => (a.name.as_str(), format!("{}_t", to_snake_case(&a.name))),
        TypeDef::Map(_)    => return,
    };
    let snake = name.replace('-', "_");
    let pfx   = format!("{mod_name}_{snake}");
    w.line(&format!("cJSON* {pfx}_to_json(const {ctype}* obj);"));
    w.line(&format!("bool   {pfx}_from_json(const cJSON* j, {ctype}* out);"));
    w.line(&format!("char*  {pfx}_encode(const {ctype}* obj);  /* caller frees */"));
    w.line(&format!("bool   {pfx}_decode(const char* s, {ctype}* out);"));
    let _ = opts;
}

fn emit_source_json(module: &IrModule, opts: &CodegenOptions) -> String {
    let name     = module.name.as_str();
    let mod_name = name.replace('-', "_");
    let mut w    = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line(&format!("#include \"{name}.h\""));
    w.blank();

    // Base64url implementation (RFC 4648 §5, no padding)
    w.line("static const char B64URL[] =");
    w.line("    \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_\";");
    w.blank();
    w.line("char* cddlc_b64url_encode(const uint8_t* data, size_t len) {");
    w.indent();
    w.line("size_t out_len = ((len + 2) / 3) * 4;");
    w.line("char* out = (char*)malloc(out_len + 1);");
    w.line("if (!out) return NULL;");
    w.line("size_t i = 0, j = 0;");
    w.line("while (i + 2 < len) {");
    w.indent();
    w.line("out[j++] = B64URL[(data[i] >> 2) & 0x3F];");
    w.line("out[j++] = B64URL[((data[i] << 4) | (data[i+1] >> 4)) & 0x3F];");
    w.line("out[j++] = B64URL[((data[i+1] << 2) | (data[i+2] >> 6)) & 0x3F];");
    w.line("out[j++] = B64URL[data[i+2] & 0x3F];");
    w.line("i += 3;");
    w.dedent();
    w.line("}");
    w.line("if (i < len) {");
    w.indent();
    w.line("out[j++] = B64URL[(data[i] >> 2) & 0x3F];");
    w.line("if (i + 1 < len) { out[j++] = B64URL[((data[i] << 4) | (data[i+1] >> 4)) & 0x3F]; out[j++] = B64URL[(data[i+1] << 2) & 0x3F]; }");
    w.line("else { out[j++] = B64URL[(data[i] << 4) & 0x3F]; }");
    w.dedent();
    w.line("}");
    w.line("out[j] = '\\0';");
    w.line("return out;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("uint8_t* cddlc_b64url_decode(const char* s, size_t* out_len) {");
    w.indent();
    w.line("static const int8_t DEC[256] = {");
    w.line("    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,");
    w.line("    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,");
    w.line("    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,");
    w.line("    52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-1,-1,-1,");
    w.line("    -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,");
    w.line("    15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,63,");
    w.line("    -1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,");
    w.line("    41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1");
    w.line("};");
    w.line("size_t slen = strlen(s);");
    w.line("*out_len = (slen * 3) / 4;");
    w.line("uint8_t* out = (uint8_t*)malloc(*out_len + 1);");
    w.line("if (!out) return NULL;");
    w.line("size_t i = 0, j = 0;");
    w.line("while (i + 3 < slen) {");
    w.indent();
    w.line("int a = DEC[(uint8_t)s[i]], b = DEC[(uint8_t)s[i+1]];");
    w.line("int c = DEC[(uint8_t)s[i+2]], d = DEC[(uint8_t)s[i+3]];");
    w.line("if (a<0||b<0||c<0||d<0) break;");
    w.line("out[j++] = (a<<2)|(b>>4);");
    w.line("out[j++] = (b<<4)|(c>>2);");
    w.line("out[j++] = (c<<6)|d;");
    w.line("i += 4;");
    w.dedent();
    w.line("}");
    w.line("if (i+1 < slen) {");
    w.indent();
    w.line("int a = DEC[(uint8_t)s[i]], b = DEC[(uint8_t)s[i+1]];");
    w.line("if (a>=0&&b>=0) out[j++]=(a<<2)|(b>>4);");
    w.line("if (i+2 < slen) { int c=DEC[(uint8_t)s[i+2]]; if(b>=0&&c>=0) out[j++]=(b<<4)|(c>>2); }");
    w.dedent();
    w.line("}");
    w.line("*out_len = j;");
    w.line("return out;");
    w.dedent();
    w.line("}");
    w.blank();

    for (_, def) in &module.types {
        emit_json_type_impl(&mut w, def, &mod_name, opts);
        w.blank();
    }

    w.finish()
}

fn emit_json_type_impl(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_json_struct_impl(w, s, mod_name, opts),
        TypeDef::Enum(e)   => emit_json_enum_impl(w, e, mod_name, opts),
        TypeDef::Array(a)  => emit_json_array_impl(w, a, mod_name, opts),
        TypeDef::Alias(a)  => emit_json_alias_impl(w, a, mod_name, opts),
        TypeDef::Map(_)    => {}
    }
}

fn json_value_expr(ty: &TypeRef, expr: &str, mod_name: &str) -> String {
    match ty {
        TypeRef::Primitive(Primitive::Bool) => format!("cJSON_CreateBool({expr})"),
        TypeRef::Primitive(Primitive::Uint) => format!("cJSON_CreateNumber((double){expr})"),
        TypeRef::Primitive(Primitive::Int)  => format!("cJSON_CreateNumber((double){expr})"),
        TypeRef::Primitive(Primitive::Float32 | Primitive::Float16
            | Primitive::Float64 | Primitive::Float) => format!("cJSON_CreateNumber((double){expr})"),
        TypeRef::Primitive(Primitive::Tstr) => format!("cJSON_CreateString({expr})"),
        TypeRef::Primitive(Primitive::Bstr | Primitive::Any) =>
            format!("cJSON_CreateString(cddlc_b64url_encode(({expr}).data, ({expr}).len))"),
        TypeRef::Primitive(Primitive::Null | Primitive::Undefined) => "cJSON_CreateNull()".into(),
        TypeRef::Named(n) => {
            let snake = n.replace('-', "_");
            format!("{mod_name}_{snake}_to_json(&{expr})")
        }
        TypeRef::Tagged(_, inner) => json_value_expr(inner, expr, mod_name),
        TypeRef::Choice(_) => "cJSON_CreateNull()".into(),
    }
}

fn emit_json_struct_impl(w: &mut IndentWriter, s: &StructDef, mod_name: &str, opts: &CodegenOptions) {
    let snake = s.name.replace('-', "_");
    let ctype = format!("{}_t", to_snake_case(&s.name));
    let pfx   = format!("{mod_name}_{snake}");

    // to_json
    w.line(&format!("cJSON* {pfx}_to_json(const {ctype}* obj) {{"));
    w.indent();
    w.line("cJSON* j = cJSON_CreateObject();");
    w.line("if (!j) return NULL;");
    for f in &s.fields {
        let fname    = f.name.replace('-', "_");
        let key      = f.name.as_str();
        let access   = format!("obj->{fname}");
        let val_expr = json_value_expr(&f.ty, &access, mod_name);
        match &f.occurrence {
            Occurrence::Optional => {
                let present_field = format!("{fname}_present");
                w.line(&format!("if (obj->{present_field}) cJSON_AddItemToObject(j, {key:?}, {val_expr});"));
            }
            _ => {
                w.line(&format!("cJSON_AddItemToObject(j, {key:?}, {val_expr});"));
            }
        }
    }
    w.line("return j;");
    w.dedent();
    w.line("}");
    w.blank();

    // from_json
    w.line(&format!("bool {pfx}_from_json(const cJSON* j, {ctype}* out) {{"));
    w.indent();
    w.line("if (!cJSON_IsObject(j)) return false;");
    w.line("memset(out, 0, sizeof(*out));");
    for f in &s.fields {
        let fname = f.name.replace('-', "_");
        let key   = f.name.as_str();
        w.line(&format!("cJSON* _{fname} = cJSON_GetObjectItemCaseSensitive(j, {key:?});"));
        match &f.occurrence {
            Occurrence::Optional => {
                let present_field = format!("{fname}_present");
                w.line(&format!("if (_{fname}) {{"));
                w.indent();
                json_decode_field(w, &f.ty, &fname, &format!("_{fname}"), mod_name, opts);
                w.line(&format!("out->{present_field} = true;"));
                w.dedent();
                w.line("}");
            }
            _ => {
                w.line(&format!("if (!_{fname}) return false;"));
                json_decode_field(w, &f.ty, &fname, &format!("_{fname}"), mod_name, opts);
            }
        }
    }
    w.line("return true;");
    w.dedent();
    w.line("}");
    w.blank();

    emit_json_encode_decode(w, &pfx, &ctype);
    let _ = opts;
}

fn json_decode_field(w: &mut IndentWriter, ty: &TypeRef, dest: &str, src: &str, mod_name: &str, _opts: &CodegenOptions) {
    match ty {
        TypeRef::Primitive(Primitive::Bool) =>
            w.line(&format!("out->{dest} = cJSON_IsTrue({src});")),
        TypeRef::Primitive(Primitive::Uint) =>
            w.line(&format!("out->{dest} = (uint64_t)cJSON_GetNumberValue({src});")),
        TypeRef::Primitive(Primitive::Int) =>
            w.line(&format!("out->{dest} = (int64_t)cJSON_GetNumberValue({src});")),
        TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) =>
            w.line(&format!("out->{dest} = (float)cJSON_GetNumberValue({src});")),
        TypeRef::Primitive(Primitive::Float64 | Primitive::Float) =>
            w.line(&format!("out->{dest} = cJSON_GetNumberValue({src});")),
        TypeRef::Primitive(Primitive::Tstr) => {
            w.line(&format!("const char* _s_{dest} = cJSON_GetStringValue({src});"));
            w.line(&format!("if (_s_{dest}) {{ strncpy(out->{dest}, _s_{dest}, sizeof(out->{dest}) - 1); }}"));
        }
        TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => {
            w.line(&format!("const char* _b64_{dest} = cJSON_GetStringValue({src});"));
            w.line(&format!("if (_b64_{dest}) {{ size_t _bl; uint8_t* _bd = cddlc_b64url_decode(_b64_{dest}, &_bl); if(_bd) {{ memcpy(out->{dest}.data, _bd, _bl); out->{dest}.len = _bl; free(_bd); }} }}"));
        }
        TypeRef::Named(n) => {
            let snake = n.replace('-', "_");
            w.line(&format!("{mod_name}_{snake}_from_json({src}, &out->{dest});"));
        }
        TypeRef::Tagged(_, inner) => json_decode_field(w, inner, dest, src, mod_name, _opts),
        _ => {}
    }
}

fn emit_json_enum_impl(w: &mut IndentWriter, e: &EnumDef, mod_name: &str, opts: &CodegenOptions) {
    let snake = e.name.replace('-', "_");
    let ctype = format!("{}_t", to_snake_case(&e.name));
    let pfx   = format!("{mod_name}_{snake}");

    w.line(&format!("cJSON* {pfx}_to_json(const {ctype}* obj) {{"));
    w.indent();
    w.line("switch (obj->tag) {");
    for v in &e.variants {
        let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
        let vsnake = v.name.replace('-', "_");
        let cddl_str = v.name.to_lowercase().replace('_', "-");
        w.line(&format!("case {vconst}:"));
        w.indent();
        match &v.ty {
            TypeRef::Primitive(Primitive::Null | Primitive::Tstr) =>
                w.line(&format!("return cJSON_CreateString({cddl_str:?});")),
            TypeRef::Primitive(Primitive::Uint) =>
                w.line(&format!("return cJSON_CreateNumber((double)obj->value.{vsnake});")),
            TypeRef::Primitive(Primitive::Int) =>
                w.line(&format!("return cJSON_CreateNumber((double)obj->value.{vsnake});")),
            TypeRef::Primitive(Primitive::Bool) =>
                w.line(&format!("return cJSON_CreateBool(obj->value.{vsnake});")),
            _ => w.line("return cJSON_CreateNull();"),
        }
        w.dedent();
    }
    w.line("default: return cJSON_CreateNull();");
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("bool {pfx}_from_json(const cJSON* j, {ctype}* out) {{"));
    w.indent();
    w.line("if (cJSON_IsString(j)) {");
    w.indent();
    w.line("const char* s = cJSON_GetStringValue(j);");
    for v in &e.variants {
        if matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)) {
            let vconst   = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
            let cddl_str = v.name.to_lowercase().replace('_', "-");
            w.line(&format!("if (strcmp(s, {cddl_str:?}) == 0) {{ out->tag = {vconst}; return true; }}"));
        }
    }
    w.line("return false;");
    w.dedent();
    w.line("}");
    let has_num = e.variants.iter().any(|v|
        matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)));
    if has_num {
        w.line("if (cJSON_IsNumber(j)) {");
        w.indent();
        for v in &e.variants {
            let vconst = format!("{}_{}", to_screaming_snake(&e.name), to_screaming_snake(&v.name));
            let vsnake = v.name.replace('-', "_");
            if matches!(&v.ty, TypeRef::Primitive(Primitive::Uint)) {
                w.line(&format!("out->tag = {vconst};"));
                w.line(&format!("out->value.{vsnake} = (uint64_t)cJSON_GetNumberValue(j);"));
                w.line("return true;");
                break;
            } else if matches!(&v.ty, TypeRef::Primitive(Primitive::Int)) {
                w.line(&format!("out->tag = {vconst};"));
                w.line(&format!("out->value.{vsnake} = (int64_t)cJSON_GetNumberValue(j);"));
                w.line("return true;");
                break;
            }
        }
        w.dedent();
        w.line("}");
    }
    w.line("return false;");
    w.dedent();
    w.line("}");
    w.blank();

    emit_json_encode_decode(w, &pfx, &ctype);
    let _ = opts;
}

fn emit_json_array_impl(w: &mut IndentWriter, a: &ArrayDef, mod_name: &str, opts: &CodegenOptions) {
    let snake = a.name.replace('-', "_");
    let ctype = format!("{}_t", to_snake_case(&a.name));
    let pfx   = format!("{mod_name}_{snake}");

    w.line(&format!("cJSON* {pfx}_to_json(const {ctype}* obj) {{"));
    w.indent();
    w.line("cJSON* arr = cJSON_CreateArray();");
    w.line("if (!arr) return NULL;");
    w.line("for (size_t i = 0; i < obj->count; i++) {");
    w.indent();
    let val_expr = json_value_expr(&a.element, "obj->items[i]", mod_name);
    w.line(&format!("cJSON_AddItemToArray(arr, {val_expr});"));
    w.dedent();
    w.line("}");
    w.line("return arr;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("bool {pfx}_from_json(const cJSON* j, {ctype}* out) {{"));
    w.indent();
    w.line("if (!cJSON_IsArray(j)) return false;");
    w.line("out->count = 0;");
    w.line("cJSON* item; cJSON_ArrayForEach(item, j) {");
    w.indent();
    w.line(&format!("if (out->count >= {}) break;", opts.max_array));
    json_decode_field(w, &a.element, "items[out->count]", "item", mod_name, opts);
    w.line("out->count++;");
    w.dedent();
    w.line("}");
    w.line("return true;");
    w.dedent();
    w.line("}");
    w.blank();

    emit_json_encode_decode(w, &pfx, &ctype);
}

fn emit_json_alias_impl(w: &mut IndentWriter, a: &AliasDef, mod_name: &str, opts: &CodegenOptions) {
    let snake      = a.name.replace('-', "_");
    let ctype      = format!("{}_t", to_snake_case(&a.name));
    let pfx        = format!("{mod_name}_{snake}");
    let is_newtype = a.tagged.is_some() || !a.constraints.is_empty();

    // to_json
    w.line(&format!("cJSON* {pfx}_to_json(const {ctype}* obj) {{"));
    w.indent();
    let inner_expr = if is_newtype { "obj->value".to_owned() } else { "(*obj)".to_owned() };
    let val_expr   = json_value_expr(&a.ty, &inner_expr, mod_name);
    w.line(&format!("return {val_expr};"));
    w.dedent();
    w.line("}");
    w.blank();

    // from_json
    w.line(&format!("bool {pfx}_from_json(const cJSON* j, {ctype}* out) {{"));
    w.indent();
    if is_newtype {
        json_decode_field(w, &a.ty, "value", "j", mod_name, opts);
    } else {
        // Simple typedef — write directly to *out
        match &a.ty {
            TypeRef::Primitive(Primitive::Uint) => {
                w.line("if (!cJSON_IsNumber(j)) return false;");
                w.line("*out = (uint64_t)cJSON_GetNumberValue(j);");
            }
            TypeRef::Primitive(Primitive::Int) => {
                w.line("if (!cJSON_IsNumber(j)) return false;");
                w.line("*out = (int64_t)cJSON_GetNumberValue(j);");
            }
            TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) => {
                w.line("if (!cJSON_IsNumber(j)) return false;");
                w.line("*out = (float)cJSON_GetNumberValue(j);");
            }
            TypeRef::Primitive(Primitive::Float64 | Primitive::Float) => {
                w.line("if (!cJSON_IsNumber(j)) return false;");
                w.line("*out = cJSON_GetNumberValue(j);");
            }
            TypeRef::Primitive(Primitive::Bool) => {
                w.line("*out = cJSON_IsTrue(j);");
            }
            TypeRef::Primitive(Primitive::Tstr) => {
                w.line("const char* _s = cJSON_GetStringValue(j);");
                w.line("if (!_s) return false;");
                w.line("strncpy(*out, _s, sizeof(*out) - 1);");
            }
            TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => {
                w.line("const char* _b64 = cJSON_GetStringValue(j);");
                w.line("if (!_b64) return false;");
                w.line("size_t _bl; uint8_t* _bd = cddlc_b64url_decode(_b64, &_bl);");
                w.line("if (!_bd) return false;");
                w.line("memcpy(out->data, _bd, _bl); out->len = _bl; free(_bd);");
            }
            _ => { w.line("(void)j;"); }
        }
    }
    w.line("return true;");
    w.dedent();
    w.line("}");
    w.blank();

    emit_json_encode_decode(w, &pfx, &ctype);
    let _ = opts;
}

fn emit_json_encode_decode(w: &mut IndentWriter, pfx: &str, ctype: &str) {
    w.line(&format!("char* {pfx}_encode(const {ctype}* obj) {{"));
    w.indent();
    w.line(&format!("cJSON* j = {pfx}_to_json(obj);"));
    w.line("if (!j) return NULL;");
    w.line("char* s = cJSON_PrintUnformatted(j);");
    w.line("cJSON_Delete(j);");
    w.line("return s;");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("bool {pfx}_decode(const char* s, {ctype}* out) {{"));
    w.indent();
    w.line("cJSON* j = cJSON_Parse(s);");
    w.line("if (!j) return false;");
    w.line(&format!("bool ok = {pfx}_from_json(j, out);"));
    w.line("cJSON_Delete(j);");
    w.line("return ok;");
    w.dedent();
    w.line("}");
}

fn emit_tests_json(module: &IrModule, opts: &CodegenOptions) -> String {
    let name     = module.name.as_str();
    let mod_name = name.replace('-', "_");
    let mut w    = IndentWriter::new(4);

    w.line("/* @generated by cddlc — do not edit manually */");
    w.line(&format!("#include \"{name}.h\""));
    w.line("#include <stdio.h>");
    w.line("#include <assert.h>");
    w.blank();

    for (_, def) in &module.types {
        emit_json_type_test(&mut w, def, &mod_name, opts);
    }

    w.blank();
    w.line("int main(void) {");
    w.indent();
    for (_, def) in &module.types {
        let tname = match def {
            TypeDef::Struct(s) => s.name.as_str(),
            TypeDef::Enum(e)   => e.name.as_str(),
            TypeDef::Array(a)  => a.name.as_str(),
            TypeDef::Alias(a)  => a.name.as_str(),
            TypeDef::Map(_)    => continue,
        };
        let snake = tname.replace('-', "_");
        w.line(&format!("test_{mod_name}_{snake}();"));
    }
    w.line("printf(\"All JSON roundtrip tests passed.\\n\");");
    w.line("return 0;");
    w.dedent();
    w.line("}");

    w.finish()
}

fn emit_json_type_test(w: &mut IndentWriter, def: &TypeDef, mod_name: &str, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => {
            let snake = s.name.replace('-', "_");
            let ctype = format!("{}_t", to_snake_case(&s.name));
            let pfx   = format!("{mod_name}_{snake}");
            w.line(&format!("static void test_{pfx}(void) {{"));
            w.indent();
            w.line(&format!("{ctype} original = {{0}};"));
            w.line(&format!("char* encoded = {pfx}_encode(&original);"));
            w.line("assert(encoded != NULL);");
            w.line(&format!("{ctype} decoded = {{0}};"));
            w.line(&format!("assert({pfx}_decode(encoded, &decoded));"));
            w.line("free(encoded);");
            w.dedent();
            w.line("}");
            w.blank();
        }
        TypeDef::Enum(e) => {
            let snake = e.name.replace('-', "_");
            let ctype = format!("{}_t", to_snake_case(&e.name));
            let pfx   = format!("{mod_name}_{snake}");
            w.line(&format!("static void test_{pfx}(void) {{"));
            w.indent();
            w.line(&format!("{ctype} original = {{0}};"));
            w.line(&format!("char* encoded = {pfx}_encode(&original);"));
            w.line("assert(encoded != NULL);");
            w.line(&format!("{ctype} decoded = {{0}};"));
            w.line(&format!("assert({pfx}_decode(encoded, &decoded));"));
            w.line("free(encoded);");
            w.dedent();
            w.line("}");
            w.blank();
        }
        TypeDef::Array(a) => {
            let snake = a.name.replace('-', "_");
            let ctype = format!("{}_t", to_snake_case(&a.name));
            let pfx   = format!("{mod_name}_{snake}");
            w.line(&format!("static void test_{pfx}(void) {{"));
            w.indent();
            w.line(&format!("{ctype} original = {{0}};"));
            w.line(&format!("char* encoded = {pfx}_encode(&original);"));
            w.line("assert(encoded != NULL);");
            w.line(&format!("{ctype} decoded = {{0}};"));
            w.line(&format!("assert({pfx}_decode(encoded, &decoded));"));
            w.line("free(encoded);");
            w.dedent();
            w.line("}");
            w.blank();
        }
        TypeDef::Alias(a) => {
            let snake = a.name.replace('-', "_");
            let ctype = format!("{}_t", to_snake_case(&a.name));
            let pfx   = format!("{mod_name}_{snake}");
            w.line(&format!("static void test_{pfx}(void) {{"));
            w.indent();
            w.line(&format!("{ctype} original = {{0}};"));
            w.line(&format!("char* encoded = {pfx}_encode(&original);"));
            w.line("assert(encoded != NULL);");
            w.line(&format!("{ctype} decoded = {{0}};"));
            w.line(&format!("assert({pfx}_decode(encoded, &decoded));"));
            w.line("free(encoded);");
            w.dedent();
            w.line("}");
            w.blank();
        }
        TypeDef::Map(_) => {}
    }
    let _ = opts;
}
